// Client tier — the browser bundle (gen_client + router + screens + handler emitters).
use super::*;
use crate::frontend::parser::*;
use std::collections::{HashMap, HashSet};

// ------------------------------------------------------------------ client.ts

pub(super) fn gen_client(program: &XeresProgram) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by xeres — browser tier. Do not edit.\n\n");
    out.push_str(RPC_RUNTIME);
    out.push('\n');
    out.push_str(UID_FN);
    out.push('\n');
    // Exact Decimal money math (spec 18): zero-dep BigInt fixed-point. Emitted
    // only when the app does Decimal arithmetic (keeps a plain bundle lean).
    if uses_decimal(program) {
        out.push_str(DECIMAL_RUNTIME);
        out.push('\n');
    }
    // Dark-mode toggle (spec 26): only emitted when the app declares a `theme
    // dark { … }` block — a plain/light-only app pays zero runtime cost.
    if program.themes.iter().any(|t| t.is_dark) {
        out.push_str(THEME_RUNTIME);
        out.push('\n');
    }

    // Enums — a string union (the variant names). String-backed end to end.
    for e in &program.enums {
        let union = e.variants.iter().map(|v| format!("\"{}\"", v)).collect::<Vec<_>>().join(" | ");
        let union = if union.is_empty() { "never".to_string() } else { union };
        out.push_str(&format!("export type {} = {};\n", e.name, union));
    }
    if !program.enums.is_empty() {
        out.push('\n');
    }

    // Model interfaces — secret fields are STRIPPED. They never reach the client.
    for m in &program.models {
        out.push_str(&format!("export interface {} {{\n", m.name));
        for p in &m.properties {
            if p.is_secret {
                out.push_str(&format!("  // {}: <stripped> — secret never crosses the wire\n", p.name));
                continue;
            }
            out.push_str(&format!("  {}: {};\n", p.name, map_ts_type(&p.data_type)));
        }
        out.push_str("}\n\n");
    }

    // Functions.
    for f in &program.functions {
        match f.env {
            EnvModifier::Server => {
                // Server fn → typed async RPC stub. The compiler writes the fetch.
                let params = f
                    .params
                    .iter()
                    .map(|p| format!("{}: {}", p.name, map_ts_type(&p.type_name)))
                    .collect::<Vec<_>>()
                    .join(", ");
                let ret = f
                    .return_type
                    .as_deref()
                    .map(map_ts_type)
                    .unwrap_or_else(|| "void".to_string());
                let arg_names = f
                    .params
                    .iter()
                    .map(|p| p.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!(
                    "// server fn — runs server-side; this is the auto-generated call site.\n\
                     export async function {name}({params}): Promise<{ret}> {{\n\
                     \x20 return __rpc(\"{name}\", [{args}]);\n\
                     }}\n\n",
                    name = f.name,
                    params = params,
                    ret = ret,
                    args = arg_names
                ));
            }
            EnvModifier::Ui | EnvModifier::None => {
                let params = f
                    .params
                    .iter()
                    .map(|p| format!("{}: {}", p.name, map_ts_type(&p.type_name)))
                    .collect::<Vec<_>>()
                    .join(", ");
                let ret = f
                    .return_type
                    .as_deref()
                    .map(map_ts_type)
                    .unwrap_or_else(|| "void".to_string());
                // A fn that awaits a server RPC is async (returns a Promise).
                let (kw, ret_ty) = if stmts_have_await(&f.body) {
                    ("export async function", format!("Promise<{}>", ret))
                } else {
                    ("export function", ret)
                };
                out.push_str(&format!("{} {}({}): {} {{\n", kw, f.name, params, ret_ty));
                for s in &f.body {
                    out.push_str(&format!("  {}\n", emit_stmt(s, "let", true)));
                }
                out.push_str("}\n\n");
            }
        }
    }

    // DOM runtime FIRST so on()/mount() exist before screens register handlers.
    if !program.screens.is_empty() {
        out.push_str(MOUNT_RUNTIME);
        out.push('\n');
    }

    // Screens + components: state cells, inline handlers, render functions.
    // (A component compiles to the same render-fn shape as a screen; it's just
    // invoked by name instead of auto-mounted.)
    let synced: HashSet<String> = program.states.iter().map(|s| s.name.clone()).collect();
    let components: HashMap<String, Vec<String>> = program
        .screens
        .iter()
        .filter(|s| s.is_component)
        .map(|s| (s.name.clone(), s.params.iter().map(|p| p.name.clone()).collect()))
        .collect();
    // Global CSS (spec 26): token name -> css var name, and every declared
    // named style, so an element's `style` slot can tell a literal CSS string
    // apart from a `style Name` class reference.
    let tokens = build_token_map(program);
    let named_styles: HashSet<String> = program.styles.iter().map(|s| s.name.clone()).collect();
    for sc in &program.screens {
        out.push_str(&gen_screen(sc, &synced, &components, &tokens, &named_styles));
    }

    // Local-first sync: the runtime + one reactive collection per `synced state`.
    if !program.states.is_empty() {
        out.push_str(SYNC_RUNTIME);
        out.push('\n');
        for st in &program.states {
            out.push_str(&format!(
                "export const {name} = new SyncedCollection<{ty}>(\"{name}\");\n",
                name = st.name,
                ty = st.collection_type
            ));
        }
        out.push('\n');
    }

    // Register zero-arg ui/none fns as named handlers, then auto-start.
    if !program.screens.is_empty() {
        for f in &program.functions {
            if f.env != EnvModifier::Server && f.params.is_empty() {
                out.push_str(&format!("on(\"{name}\", {name});\n", name = f.name));
            }
        }
        // Redraw the view whenever a synced collection changes (local or pulled).
        for st in &program.states {
            out.push_str(&format!(
                "{name}.subscribe(() => {{ if (__draw) __draw(); }});\n",
                name = st.name
            ));
        }
        out.push_str(&gen_router(program));
    }

    out
}

/// The client router (P2): a route map over the prop-less, non-component
/// screens, `__navigate` (switch screen + push the URL), back/forward via
/// `popstate`, and `__start` (mount + resolve the initial URL). Each navigable
/// screen gets a path — the first/default screen is `/`, the rest `/<name>`.
/// A screen's `on load` runs whenever it's navigated to (generalizing P1's
/// mount hook). Empty when the program has no mountable screen (unchanged: no
/// auto-mount, as before).
fn gen_router(program: &XeresProgram) -> String {
    let navigable: Vec<&crate::frontend::parser::ScreenNode> = program
        .screens
        .iter()
        .filter(|s| !s.is_component && s.params.is_empty())
        .collect();
    let Some(default) = navigable.first() else {
        return String::new();
    };
    let path_of = |sc: &crate::frontend::parser::ScreenNode| -> String {
        if sc.name == default.name {
            "/".to_string()
        } else {
            format!("/{}", sc.name.to_lowercase())
        }
    };

    // Param routes (`route "/post/:id"`) match by pattern, not an exact path, so
    // they join the render/loader maps but not __path/__byPath. R32 keeps a param
    // route's props in sync with its `:name` segments.
    let param_routes: Vec<&crate::frontend::parser::ScreenNode> =
        program.screens.iter().filter(|s| !s.is_component && s.route.is_some()).collect();
    let all_routes: Vec<&crate::frontend::parser::ScreenNode> =
        navigable.iter().copied().chain(param_routes.iter().copied()).collect();

    let render = all_routes
        .iter()
        .map(|s| format!("{:?}: {}", s.name, s.name))
        .collect::<Vec<_>>()
        .join(", ");
    let paths = navigable
        .iter()
        .map(|s| format!("{:?}: {:?}", s.name, path_of(s)))
        .collect::<Vec<_>>()
        .join(", ");
    let by_path = navigable
        .iter()
        .map(|s| format!("{:?}: {:?}", path_of(s), s.name))
        .collect::<Vec<_>>()
        .join(", ");
    let loaders = all_routes
        .iter()
        .filter(|s| !s.load.is_empty())
        .map(|s| format!("{:?}: {}__load", s.name, s.name))
        .collect::<Vec<_>>()
        .join(", ");
    // R31 — protected (`auth`) routes the client router redirects away from when
    // the readable `xeres_auth` flag cookie is absent (server enforces too).
    let protected = navigable
        .iter()
        .filter(|s| s.is_auth)
        .map(|s| format!("{:?}: true", s.name))
        .collect::<Vec<_>>()
        .join(", ");
    // R32 — each param route as { screen, segs }: the URL pattern split on `/`,
    // with `:name` segments captured at match time and substituted on navigate.
    let param_route_entries = param_routes
        .iter()
        .map(|s| {
            let segs = s
                .route
                .as_deref()
                .unwrap_or("")
                .split('/')
                .map(|seg| format!("{:?}", seg))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ screen: {:?}, segs: [{}] }}", s.name, segs)
        })
        .collect::<Vec<_>>()
        .join(", ");

    format!(
        r#"
// ---- xeres client router ----
const __render: Record<string, () => string> = {{ {render} }};
const __path: Record<string, string> = {{ {paths} }};
const __byPath: Record<string, string> = {{ {by_path} }};
const __loaders: Record<string, () => void | Promise<void>> = {{ {loaders} }};
const __defaultScreen = {default:?};
const __protected: Record<string, boolean> = {{ {protected} }};
let __screen = __defaultScreen;
let __params: Record<string, string> = {{}};
const __paramRoutes: Array<{{ screen: string; segs: string[] }}> = [ {param_routes} ];

// R32 — match a URL against the param-route patterns; on a hit, capture the
// `:name` segments into __params (the matched screen reads them, coerced).
function __matchRoute(path: string): string | null {{
  const parts = path.split("/");
  for (const r of __paramRoutes) {{
    if (r.segs.length !== parts.length) continue;
    const cap: Record<string, string> = {{}};
    let ok = true;
    for (let i = 0; i < r.segs.length; i++) {{
      const seg = r.segs[i];
      if (seg.startsWith(":")) cap[seg.slice(1)] = decodeURIComponent(parts[i]);
      else if (seg !== parts[i]) {{ ok = false; break; }}
    }}
    if (ok) {{ __params = cap; return r.screen; }}
  }}
  return null;
}}

// `navigate(Screen {{ id: x }})` (R32): set the params, build the URL from the
// route pattern, switch screen, run its loader.
export function __navigateTo(screen: string, params: Record<string, string>): void {{
  const r = __paramRoutes.find((x) => x.screen === screen);
  if (!r) return;
  __params = params;
  __screen = screen;
  const path = r.segs.map((s) => s.startsWith(":") ? encodeURIComponent(params[s.slice(1)] ?? "") : s).join("/") || "/";
  if (typeof history !== "undefined") history.pushState({{}}, "", path);
  if (__draw) __draw();
  const l = __loaders[screen]; if (l) l();
}}

// R31 — the readable `xeres_auth` flag (set alongside the HttpOnly session on
// login) lets the router bounce unauthenticated users off `auth` routes. It is
// only a UX hint: forging it reveals an empty shell, since data still needs the
// signed session (R24), and the server applies the same guard on shell requests.
function __authed(): boolean {{
  return typeof document !== "undefined"
    && document.cookie.split(";").some((c) => c.trim().startsWith("xeres_auth="));
}}
function __guard(name: string): string {{
  return (__protected[name] && !__authed()) ? __defaultScreen : name;
}}

export function __navigate(name: string): void {{
  if (!(name in __render)) return;
  name = __guard(name);
  __screen = name;
  if (typeof history !== "undefined") history.pushState({{}}, "", __path[name]);
  if (__draw) __draw();
  const l = __loaders[name]; if (l) l();
}}

function __routeFromUrl(): void {{
  const p = (typeof location !== "undefined") ? location.pathname : "/";
  __screen = __guard(__byPath[p] || __matchRoute(p) || __defaultScreen);
}}

if (typeof window !== "undefined") {{
  window.addEventListener("popstate", () => {{
    __routeFromUrl();
    if (__draw) __draw();
    const l = __loaders[__screen]; if (l) l();
  }});
}}

export function __start(rootId: string): void {{
  const el = document.getElementById(rootId);
  __routeFromUrl();
  if (el) mount(el, () => __render[__screen]());
  const l = __loaders[__screen]; if (l) l();
}}
__start("app");
"#,
        render = render,
        paths = paths,
        by_path = by_path,
        loaders = loaders,
        protected = protected,
        param_routes = param_route_entries,
        default = default.name,
    )
}

/// Emit one screen: its `state` object, inline click-handler functions, and a
/// reactive render function (re-reads state each draw).
fn gen_screen(
    sc: &crate::frontend::parser::ScreenNode,
    synced: &HashSet<String>,
    components: &HashMap<String, Vec<String>>,
    tokens: &HashMap<String, String>,
    named_styles: &HashSet<String>,
) -> String {
    let mut out = String::new();
    let state_vars: HashSet<String> = sc.states.iter().map(|s| s.name.clone()).collect();

    if !sc.states.is_empty() {
        let inits = sc
            .states
            .iter()
            .map(|s| format!("{}: {}", s.name, emit_expr(&s.init, true)))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("const {}_state = {{ {} }};\n", sc.name, inits));
    }

    let mut em = ScreenEmit {
        screen: sc.name.clone(),
        state_vars,
        synced: synced.clone(),
        components: components.clone(),
        tokens: tokens.clone(),
        named_styles: named_styles.clone(),
        handlers: String::new(),
        hcount: 0,
        loop_ctx: None,
    };
    let render_expr = em.nodes(&sc.body);
    out.push_str(&em.handlers);

    // A param route (`route "/post/:id"`) reads its props from the router's
    // `__params` (coerced by type), so its render/loader take no arguments; a
    // component takes its props as function args; a plain screen has none.
    let is_param_route = sc.route.is_some() && !sc.is_component;
    let (props, param_reads) = if is_param_route {
        let reads = sc
            .params
            .iter()
            .map(|p| {
                let v = if p.type_name == "Int" {
                    format!("Number(__params[{:?}])", p.name)
                } else {
                    format!("__params[{:?}]", p.name)
                };
                format!("  const {} = {};\n", p.name, v)
            })
            .collect::<String>();
        (String::new(), reads)
    } else {
        let props = sc
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, map_ts_type(&p.type_name)))
            .collect::<Vec<_>>()
            .join(", ");
        (props, String::new())
    };
    let destr = if sc.states.is_empty() {
        String::new()
    } else {
        let names = sc
            .states
            .iter()
            .map(|s| s.name.clone())
            .collect::<Vec<_>>()
            .join(", ");
        format!("  const {{ {} }} = {}_state;\n", names, sc.name)
    };
    out.push_str(&format!(
        "export function {}({}): string {{\n{}{}  return {};\n}}\n\n",
        sc.name, props, param_reads, destr, render_expr
    ));

    // `on load { … }` — an async lifecycle fn run once on mount (P1). It may
    // await server fns; after it settles it triggers a redraw so fetched data
    // shows. State assignments rewrite to `<Screen>_state.x` via emit_h_stmt.
    if !sc.load.is_empty() {
        let body = sc
            .load
            .iter()
            .map(|s| emit_h_stmt(s, &sc.name, &em.state_vars))
            .collect::<Vec<_>>()
            .join("\n  ");
        out.push_str(&format!(
            "export async function {sc}__load(): Promise<void> {{\n{reads}  {body}\n  if (__draw) __draw();\n}}\n\n",
            sc = sc.name,
            reads = param_reads,
            body = body
        ));
    }
    out
}

/// Where a `for` loop's items live, so per-item handlers can re-look-up the
/// bound item from its key at click time (event delegation).
#[derive(Clone)]
struct LoopCtx {
    var: String,
    /// JS expression (in module/handler scope) that yields the backing store:
    /// a `SyncedCollection` (keyed by `id`) or an array (keyed by index).
    source: String,
    synced: bool,
    /// For an array loop, the index binding name (`for x in arr` -> arr.map((x,
    /// idx)=>…)); items are re-bound by index, which works for any element type.
    index: Option<String>,
}

/// Walks a screen's view, allocating named handlers for inline `-> { ... }`
/// blocks and rewriting `state` reads/writes to the screen's state object.
struct ScreenEmit {
    screen: String,
    state_vars: HashSet<String>,
    /// Names of program-level `synced state` collections (iterate via `.all()`).
    synced: HashSet<String>,
    /// Component name -> its param names in declaration order (named args at a
    /// call site are reordered to this positional order).
    components: HashMap<String, Vec<String>>,
    /// Theme token name -> css var name (spec 26); resolves `token(x)` in a
    /// literal `style "…"` string.
    tokens: HashMap<String, String>,
    /// Declared `style Name` names (spec 26); an element `style Name` whose
    /// name is in this set renders as `class="x-name"` instead of inline CSS.
    named_styles: HashSet<String>,
    handlers: String,
    hcount: usize,
    /// When inside `for var in <iterable>`, how to re-bind items in handlers.
    loop_ctx: Option<LoopCtx>,
}

impl ScreenEmit {
    fn nodes(&mut self, nodes: &[ViewNode]) -> String {
        match nodes.len() {
            0 => "\"\"".to_string(),
            1 => self.node(&nodes[0]),
            _ => {
                let mut s = String::from("`");
                for n in nodes {
                    s.push_str("${");
                    s.push_str(&self.node(n));
                    s.push('}');
                }
                s.push('`');
                s
            }
        }
    }

    fn node(&mut self, v: &ViewNode) -> String {
        match v {
            ViewNode::Element { tag, arg, style, bind, event, children } => {
                // `link "Label" -> Screen` — a client-router anchor. The `->`
                // slot is a navigation target (checker R28), so it's rendered
                // specially (href from the route map + data-link), not via the
                // generic element path.
                if tag == "link" {
                    return link_node(arg, style, event, &self.tokens, &self.named_styles);
                }
                let html = map_tag(tag);
                let void = is_void(html);
                let mut s = String::from("`<");
                s.push_str(html);
                // Layout + styling. `row`/`column` are flex containers; an
                // explicit `style "..."` takes over the element's look (and
                // drops the default class so global rules don't fight it).
                let base_layout = match tag.as_str() {
                    "row" => Some("display:flex;flex-direction:row;"),
                    "column" => Some("display:flex;flex-direction:column;"),
                    "grid" => Some("display:grid;"),
                    _ => None,
                };
                match style {
                    // `style Name` (spec 26) — a declared named style compiles
                    // to a class, not an inline `style=`; a row/col still gets
                    // its layout class alongside it (the named style is sugar
                    // over the generated sheet, not a replacement for layout).
                    Some(Expr::Ident(name)) if self.named_styles.contains(name) => {
                        let mut classes = Vec::new();
                        match tag.as_str() {
                            "row" => classes.push("x-row".to_string()),
                            "column" => classes.push("x-col".to_string()),
                            _ => {}
                        }
                        classes.push(format!("x-{}", name.to_lowercase()));
                        s.push_str(&format!(" class=\"{}\"", classes.join(" ")));
                    }
                    Some(style_expr) => {
                        s.push_str(" style=\"");
                        if let Some(base) = base_layout {
                            s.push_str(base);
                        }
                        match style_expr {
                            // a literal CSS string is inlined (tokens resolved, whitespace tidied)
                            Expr::Str(css) => s.push_str(&inline_css(&resolve_tokens(css, &self.tokens))),
                            // a dynamic style expression is interpolated
                            e => {
                                s.push_str("${");
                                s.push_str(&emit_expr(e, true));
                                s.push('}');
                            }
                        }
                        s.push('"');
                    }
                    None => match tag.as_str() {
                        "row" => s.push_str(" class=\"x-row\""),
                        "column" => s.push_str(" class=\"x-col\""),
                        _ => {}
                    },
                }
                match event {
                    Some(Handler::Call(e)) => {
                        s.push_str(" data-onclick=\"");
                        s.push_str(&emit_expr(e, true));
                        s.push('"');
                    }
                    Some(Handler::Block(stmts)) => {
                        let hname = format!("{}_h{}", self.screen, self.hcount);
                        self.hcount += 1;
                        let body: String = stmts
                            .iter()
                            .map(|st| emit_h_stmt(st, &self.screen, &self.state_vars))
                            .collect::<Vec<_>>()
                            .join(" ");
                        let kw = if stmts_have_await(stmts) { "async function" } else { "function" };
                        if let Some(ctx) = self.loop_ctx.clone() {
                            // Inside a `for`: re-bind the item from its key at
                            // click time (event delegation). Synced collections
                            // key by `id` (`.get`); arrays key by index (`[i]`),
                            // which works for any element type incl. primitives.
                            let (lookup, key) = if ctx.synced {
                                (format!("{}.get(__key)", ctx.source), format!("{}.id", ctx.var))
                            } else {
                                let idx = ctx.index.clone().unwrap_or_else(|| "0".to_string());
                                (format!("{}[__key]", ctx.source), idx)
                            };
                            self.handlers.push_str(&format!(
                                "{kw} {h}(__key) {{ const {v} = {lookup}; {b} }}\non(\"{h}\", {h});\n",
                                kw = kw, h = hname, v = ctx.var, lookup = lookup, b = body
                            ));
                            s.push_str(" data-onclick=\"");
                            s.push_str(&hname);
                            s.push_str("\" data-key=\"${__esc(");
                            s.push_str(&key);
                            s.push_str(")}\"");
                        } else {
                            self.handlers.push_str(&format!(
                                "{kw} {h}() {{ {b} }}\non(\"{h}\", {h});\n",
                                kw = kw, h = hname, b = body
                            ));
                            s.push_str(" data-onclick=\"");
                            s.push_str(&hname);
                            s.push('"');
                        }
                    }
                    None => {}
                }
                // void elements: input type, image src, or input placeholder.
                if void {
                    if tag == "password" {
                        s.push_str(" type=\"password\"");
                    }
                    if tag == "checkbox" {
                        s.push_str(" type=\"checkbox\"");
                    }
                    if tag == "number" {
                        s.push_str(" type=\"number\"");
                    }
                    if tag == "image" {
                        // the (string) arg is the image src — escaped (R22).
                        if let Some(e) = arg {
                            s.push_str(" src=\"${__esc(");
                            s.push_str(&emit_expr(e, true));
                            s.push_str(")}\"");
                        }
                    } else if let Some(Expr::Str(ph)) = arg {
                        s.push_str(" placeholder=\"");
                        s.push_str(ph);
                        s.push('"');
                    }
                }
                // two-way bind. `checkbox` reflects a Bool via `checked` (runtime
                // reads node.checked); `textarea` reflects via element content
                // (added below); everything else reflects via the `value` attr.
                if let Some(var) = bind {
                    let bname = format!("{}:{}", self.screen, var);
                    self.handlers.push_str(&format!(
                        "onBind(\"{bn}\", (v) => {{ {sc}_state.{v} = v; }});\n",
                        bn = bname,
                        sc = self.screen,
                        v = var
                    ));
                    if tag == "checkbox" {
                        s.push_str(" ${");
                        s.push_str(var);
                        s.push_str(" ? \"checked\" : \"\"} data-bind=\"");
                        s.push_str(&bname);
                        s.push('"');
                    } else if tag == "textarea" || tag == "select" {
                        s.push_str(" data-bind=\"");
                        s.push_str(&bname);
                        s.push('"');
                    } else if tag == "radio" {
                        // the data-bind + name go on each generated input (content).
                    } else {
                        s.push_str(" value=\"${__esc(");
                        s.push_str(var);
                        s.push_str(")}\" data-bind=\"");
                        s.push_str(&bname);
                        s.push('"');
                    }
                }
                if void {
                    s.push_str(" />`");
                    return s;
                }
                s.push('>');
                // A bound `textarea` carries its value as element content; a
                // `select` generates `<option>`s from its list arg (the bound
                // value is the selected one); every other tag emits its arg.
                if tag == "textarea" {
                    if let Some(var) = bind {
                        s.push_str("${__esc(");
                        s.push_str(var);
                        s.push_str(")}");
                    }
                } else if tag == "select" {
                    if let (Some(var), Some(opts)) = (bind, arg) {
                        s.push_str("${(");
                        s.push_str(&emit_expr(opts, true));
                        s.push_str(").map((__o) => `<option ${(");
                        s.push_str(var);
                        s.push_str(") === __o ? \"selected\" : \"\"}>${__esc(__o)}</option>`).join(\"\")}");
                    }
                } else if tag == "radio" {
                    if let (Some(var), Some(opts)) = (bind, arg) {
                        let bname = format!("{}:{}", self.screen, var);
                        s.push_str("${(");
                        s.push_str(&emit_expr(opts, true));
                        s.push_str(").map((__o) => `<label><input type=\"radio\" name=\"");
                        s.push_str(&bname);
                        s.push_str("\" value=\"${__esc(__o)}\" ${(");
                        s.push_str(var);
                        s.push_str(") === __o ? \"checked\" : \"\"} data-bind=\"");
                        s.push_str(&bname);
                        s.push_str("\" />${__esc(__o)}</label>`).join(\"\")}");
                    }
                } else {
                    match arg {
                        Some(Expr::Str(t)) => s.push_str(t),
                        // `raw(...)` — the single audited un-escaped HTML sink (R22).
                        Some(Expr::Raw(inner)) => {
                            s.push_str("${");
                            s.push_str(&emit_expr(inner, true));
                            s.push('}');
                        }
                        // Default: every interpolated value is HTML-escaped (R22).
                        Some(e) => {
                            s.push_str("${__esc(");
                            s.push_str(&emit_expr(e, true));
                            s.push_str(")}");
                        }
                        None => {}
                    }
                }
                for c in children {
                    s.push_str("${");
                    s.push_str(&self.node(c));
                    s.push('}');
                }
                s.push_str("</");
                s.push_str(html);
                s.push_str(">`");
                s
            }
            ViewNode::For { var, iter, body } => {
                // Is this a `synced` collection (iterate via `.all()`) or a
                // plain `List<T>` cell / prop (a JS array, iterate directly)?
                let synced = matches!(iter, Expr::Ident(c) if self.synced.contains(c));
                // Where handlers in the body re-look-up an item by its key:
                // synced -> the module-level collection; a screen `state` array
                // -> `<Screen>_state.<name>`; a prop array -> the prop name.
                let source = match iter {
                    Expr::Ident(c) if synced => Some(c.clone()),
                    Expr::Ident(c) if self.state_vars.contains(c) => {
                        Some(format!("{}_state.{}", self.screen, c))
                    }
                    Expr::Ident(c) => Some(c.clone()),
                    _ => None,
                };
                let index = if synced { None } else { Some(format!("__i_{}", var)) };
                let prev = self.loop_ctx.take();
                self.loop_ctx = source.map(|src| LoopCtx {
                    var: var.clone(),
                    source: src,
                    synced,
                    index: index.clone(),
                });
                let body_js = self.nodes(body);
                self.loop_ctx = prev;
                if synced {
                    format!("{}.all().map(({}) => {}).join(\"\")", emit_expr(iter, true), var, body_js)
                } else {
                    // Array: bind the index too, so handlers can re-key items.
                    format!(
                        "{}.map(({}, {}) => {}).join(\"\")",
                        emit_expr(iter, true),
                        var,
                        index.unwrap_or_else(|| "__i".to_string()),
                        body_js
                    )
                }
            }
            ViewNode::If { cond, then_body, else_body } => {
                let then_js = self.nodes(then_body);
                let else_js = self.nodes(else_body);
                format!("({} ? {} : {})", emit_expr(cond, true), then_js, else_js)
            }
            ViewNode::Component { name, args, .. } => {
                // Invoke the component's render fn with named args reordered to
                // the component's declared param order.
                let order = self.components.get(name);
                let positional: Vec<String> = match order {
                    Some(params) => params
                        .iter()
                        .map(|pname| {
                            args.iter()
                                .find(|(f, _)| f == pname)
                                .map(|(_, v)| emit_expr(v, true))
                                .unwrap_or_else(|| "undefined".to_string())
                        })
                        .collect(),
                    // Unknown component (checker already errored): emit args as-is.
                    None => args.iter().map(|(_, v)| emit_expr(v, true)).collect(),
                };
                format!("{}({})", name, positional.join(", "))
            }
        }
    }
}

/// Handler-statement emitter: rewrites `state` cells to `<Screen>_state.x`.
fn emit_h_stmt(s: &Stmt, screen: &str, sv: &HashSet<String>) -> String {
    match s {
        Stmt::Assign { name, value } => {
            let target = if sv.contains(name) {
                format!("{}_state.{}", screen, name)
            } else {
                name.clone()
            };
            format!("{} = {};", target, emit_h_expr(value, screen, sv))
        }
        Stmt::Let { name, value, .. } => format!("let {} = {};", name, emit_h_expr(value, screen, sv)),
        Stmt::Return(e) => format!("return {};", emit_h_expr(e, screen, sv)),
        Stmt::Expr(e) => format!("{};", emit_h_expr(e, screen, sv)),
        Stmt::Try { body, handler } => {
            let b = body.iter().map(|x| emit_h_stmt(x, screen, sv)).collect::<Vec<_>>().join(" ");
            let h = handler.iter().map(|x| emit_h_stmt(x, screen, sv)).collect::<Vec<_>>().join(" ");
            format!("try {{ {} }} catch (_e) {{ {} }}", b, h)
        }
        Stmt::If { cond, then_body, else_body } => {
            let then = then_body.iter().map(|x| emit_h_stmt(x, screen, sv)).collect::<Vec<_>>().join(" ");
            if else_body.is_empty() {
                format!("if ({}) {{ {} }}", emit_h_expr(cond, screen, sv), then)
            } else {
                let els = else_body.iter().map(|x| emit_h_stmt(x, screen, sv)).collect::<Vec<_>>().join(" ");
                format!("if ({}) {{ {} }} else {{ {} }}", emit_h_expr(cond, screen, sv), then, els)
            }
        }
        Stmt::For { var, iter, body } => {
            let b = body.iter().map(|x| emit_h_stmt(x, screen, sv)).collect::<Vec<_>>().join(" ");
            if let Expr::Range { start, end } = iter {
                format!(
                    "for (let {v} = {s}; {v} < {e}; {v}++) {{ {b} }}",
                    v = var, s = emit_h_expr(start, screen, sv), e = emit_h_expr(end, screen, sv), b = b
                )
            } else {
                format!("for (const {v} of {it}) {{ {b} }}", v = var, it = emit_h_expr(iter, screen, sv), b = b)
            }
        }
        Stmt::While { cond, body } => {
            let b = body.iter().map(|x| emit_h_stmt(x, screen, sv)).collect::<Vec<_>>().join(" ");
            format!("while ({}) {{ {} }}", emit_h_expr(cond, screen, sv), b)
        }
        Stmt::Break => "break;".to_string(),
        Stmt::Continue => "continue;".to_string(),
        Stmt::Match { scrutinee, arms } => {
            let mut out = format!("switch ({}) {{ ", emit_h_expr(scrutinee, screen, sv));
            for arm in arms {
                match &arm.pattern {
                    MatchPat::Wildcard => out.push_str("default: { "),
                    MatchPat::Variant(v) => out.push_str(&format!("case {:?}: {{ ", v)),
                }
                let b = arm.body.iter().map(|x| emit_h_stmt(x, screen, sv)).collect::<Vec<_>>().join(" ");
                out.push_str(&b);
                out.push_str(" break; } ");
            }
            out.push('}');
            out
        }
        // `transaction` is server-only (R33); a ui handler never contains one.
        Stmt::Transaction(_) => String::new(),
    }
}

fn emit_h_expr(e: &Expr, screen: &str, sv: &HashSet<String>) -> String {
    match e {
        Expr::Ident(v) => {
            if sv.contains(v) {
                format!("{}_state.{}", screen, v)
            } else {
                v.clone()
            }
        }
        Expr::Int(n) => n.to_string(),
        Expr::Float(f) => format!("{:?}", f),
        Expr::Str(s) => format!("{:?}", s),
        Expr::Bool(b) => b.to_string(),
        Expr::Field { base, field } => {
            if let Expr::Ident(name) = base.as_ref() {
                if name.chars().next().map(|c| c.is_uppercase()).unwrap_or(false) {
                    return format!("{:?}", field); // `Enum.Variant` -> variant string
                }
            }
            format!("{}.{}", emit_h_expr(base, screen, sv), field)
        }
        Expr::Call { callee, args } => {
            if callee == "now" && args.is_empty() {
                return "Date.now()".to_string();
            }
            // decimal("19.99") — string-backed money; forward the inner string.
            if callee == "decimal" {
                return args
                    .first()
                    .map(|x| emit_h_expr(x, screen, sv))
                    .unwrap_or_else(|| "\"\"".to_string());
            }
            // Lowered Decimal ops (spec 18) → the zero-dep `__dec.*` BigInt runtime.
            if let Some(op) = callee.strip_prefix("__dec_") {
                let a = args.first().map(|x| emit_h_expr(x, screen, sv)).unwrap_or_default();
                let b = args.get(1).map(|x| emit_h_expr(x, screen, sv)).unwrap_or_default();
                return format!("__dec.{}({}, {})", op, a, b);
            }
            // `__list_contains(list, x)` — lowered `List.contains` (spec 19); a
            // structural (JSON) match so it agrees with the server/interp.
            if callee == "__list_contains" {
                let list = args.first().map(|x| emit_h_expr(x, screen, sv)).unwrap_or_default();
                let needle = args.get(1).map(|x| emit_h_expr(x, screen, sv)).unwrap_or_default();
                return format!("{}.some((__e) => JSON.stringify(__e) === JSON.stringify({}))", list, needle);
            }
            // Lowered `String + <scalar>` (spec 24) → JS `+` seeded with `""`.
            if callee == "__str_concat" {
                let a = args.first().map(|x| emit_h_expr(x, screen, sv)).unwrap_or_default();
                let b = args.get(1).map(|x| emit_h_expr(x, screen, sv)).unwrap_or_default();
                return format!("(\"\" + ({}) + ({}))", a, b);
            }
            // `navigate(Screen)` — the argument is a screen *name* (R28), lowered
            // to the router's `__navigate("Screen")` (switch screen + URL). A
            // `navigate(Screen { id: x })` is a typed-route-param nav (R32) →
            // `__navigateTo`, which builds the URL from the route pattern.
            if callee == "navigate" {
                if let Some(Expr::Record { name, fields }) = args.first() {
                    let ps = fields
                        .iter()
                        .map(|(f, v)| format!("{:?}: String({})", f, emit_h_expr(v, screen, sv)))
                        .collect::<Vec<_>>()
                        .join(", ");
                    return format!("__navigateTo({:?}, {{ {} }})", name, ps);
                }
                return format!("__navigate({})", nav_target_js(args));
            }
            // `toggle_theme()` (spec 26) — browser-only builtin, flips
            // `data-theme` on `<html>` + persists to `localStorage`.
            if callee == "toggle_theme" {
                return "__toggleTheme()".to_string();
            }
            let a: Vec<String> = args.iter().map(|x| emit_h_expr(x, screen, sv)).collect();
            let arg = |i: usize| a.get(i).cloned().unwrap_or_default();
            match callee.as_str() {
                "abs" => return format!("Math.abs({})", arg(0)),
                "min" => return format!("Math.min({}, {})", arg(0), arg(1)),
                "max" => return format!("Math.max({}, {})", arg(0), arg(1)),
                _ => {}
            }
            format!("{}({})", callee, a.join(", "))
        }
        Expr::Unary { op, expr } => {
            let sym = match op {
                UnOp::Neg => "-",
                UnOp::Not => "!",
            };
            format!("{}{}", sym, emit_h_expr(expr, screen, sv))
        }
        Expr::Binary { op, left, right } => format!(
            "({} {} {})",
            emit_h_expr(left, screen, sv),
            binop_sym(*op),
            emit_h_expr(right, screen, sv)
        ),
        Expr::Declassify(inner) | Expr::Raw(inner) => emit_h_expr(inner, screen, sv),
        Expr::Await(inner) => format!("await {}", emit_h_expr(inner, screen, sv)),
        Expr::MethodCall { receiver, method, args } => {
            if method == "or" && args.len() == 1 {
                return format!(
                    "({} ?? {})",
                    emit_h_expr(receiver, screen, sv),
                    emit_h_expr(&args[0], screen, sv)
                );
            }
            let recv = emit_h_expr(receiver, screen, sv);
            // Higher-order list ops (spec 19) — Array.map/filter/reduce; reduce's
            // args are `(callback, init)`, so reverse our `(init, closure)`.
            match method.as_str() {
                "map" if args.len() == 1 => {
                    return format!("{}.map({})", recv, emit_h_expr(&args[0], screen, sv))
                }
                "filter" if args.len() == 1 => {
                    return format!("{}.filter({})", recv, emit_h_expr(&args[0], screen, sv))
                }
                "reduce" if args.len() == 2 => {
                    return format!(
                        "{}.reduce({}, {})",
                        recv,
                        emit_h_expr(&args[1], screen, sv),
                        emit_h_expr(&args[0], screen, sv)
                    )
                }
                _ => {}
            }
            let a: Vec<String> = args.iter().map(|x| emit_h_expr(x, screen, sv)).collect();
            if let Some(s) = emit_string_method(&recv, method, &a, true) {
                return s;
            }
            format!("{}.{}({})", recv, method, a.join(", "))
        }
        Expr::NoneLit => "null".to_string(),
        Expr::ListLit(items) => {
            let body = items.iter().map(|x| emit_h_expr(x, screen, sv)).collect::<Vec<_>>().join(", ");
            format!("[{}]", body)
        }
        Expr::Ternary { cond, then, otherwise } => format!(
            "({} ? {} : {})",
            emit_h_expr(cond, screen, sv),
            emit_h_expr(then, screen, sv),
            emit_h_expr(otherwise, screen, sv)
        ),
        // Record in a handler is a client object literal; rewrite state refs.
        Expr::Record { fields, .. } => {
            let body = fields
                .iter()
                .map(|(f, v)| format!("{}: {}", f, emit_h_expr(v, screen, sv)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ {} }}", body)
        }
        Expr::Range { start, end } => format!(
            "Array.from({{length: ({e}) - ({s})}}, (_, __i) => __i + ({s}))",
            s = emit_h_expr(start, screen, sv), e = emit_h_expr(end, screen, sv)
        ),
        // Closure (spec 19): an arrow fn in the view tier.
        Expr::Closure { params, body } => {
            format!("({}) => {}", params.join(", "), emit_h_expr(body, screen, sv))
        }
        // `xs[i]` → `.at(i)` → Optional<T> (`?? null`).
        Expr::Index { base, index } => {
            let b = emit_h_expr(base, screen, sv);
            let i = emit_h_expr(index, screen, sv);
            emit_list_method(&b, "at", &[i], true).unwrap_or_default()
        }
    }
}

/// Does a body / expression contain an `await` (so its fn must be `async`)?
fn stmts_have_await(stmts: &[Stmt]) -> bool {
    stmts.iter().any(|s| match s {
        Stmt::Let { value, .. }
        | Stmt::Assign { value, .. }
        | Stmt::Return(value)
        | Stmt::Expr(value) => expr_has_await(value),
        Stmt::Try { body, handler } => stmts_have_await(body) || stmts_have_await(handler),
        Stmt::If { cond, then_body, else_body } => {
            expr_has_await(cond) || stmts_have_await(then_body) || stmts_have_await(else_body)
        }
        Stmt::For { iter, body, .. } => expr_has_await(iter) || stmts_have_await(body),
        Stmt::While { cond, body } => expr_has_await(cond) || stmts_have_await(body),
        Stmt::Match { scrutinee, arms } => {
            expr_has_await(scrutinee) || arms.iter().any(|a| stmts_have_await(&a.body))
        }
        Stmt::Transaction(body) => stmts_have_await(body),
        Stmt::Break | Stmt::Continue => false,
    })
}

fn expr_has_await(e: &Expr) -> bool {
    match e {
        Expr::Await(_) => true,
        Expr::Field { base, .. } => expr_has_await(base),
        Expr::Call { args, .. } => args.iter().any(expr_has_await),
        Expr::Unary { expr, .. } => expr_has_await(expr),
        Expr::Binary { left, right, .. } => expr_has_await(left) || expr_has_await(right),
        Expr::Declassify(inner) | Expr::Raw(inner) => expr_has_await(inner),
        Expr::MethodCall { receiver, args, .. } => {
            expr_has_await(receiver) || args.iter().any(expr_has_await)
        }
        Expr::Record { fields, .. } => fields.iter().any(|(_, v)| expr_has_await(v)),
        Expr::ListLit(items) => items.iter().any(expr_has_await),
        Expr::Ternary { cond, then, otherwise } => {
            expr_has_await(cond) || expr_has_await(then) || expr_has_await(otherwise)
        }
        Expr::Range { start, end } => expr_has_await(start) || expr_has_await(end),
        Expr::Closure { body, .. } => expr_has_await(body),
        Expr::Index { base, index } => expr_has_await(base) || expr_has_await(index),
        Expr::Int(_) | Expr::Float(_) | Expr::Str(_) | Expr::Bool(_) | Expr::Ident(_)
        | Expr::NoneLit => false,
    }
}

const MOUNT_RUNTIME: &str = include_str!("../../../runtime/mount_runtime.ts");
