// Server tier — the emitted std-only Rust server (gen_server + inbound api + RPC/decoding helpers).
use super::*;
use crate::frontend::parser::*;
use std::collections::HashSet;

// ------------------------------------------------------------------ server.rs

pub(super) fn gen_server(program: &XeresProgram) -> String {
    let models: HashSet<&str> = program.models.iter().map(|m| m.name.as_str()).collect();

    let mut out = String::new();
    out.push_str("// GENERATED by xeres — server tier (std-only HTTP). Do not edit.\n");
    out.push_str("#![allow(dead_code, unused_variables, unused_parens, unused_mut)]\n\n");
    out.push_str(SERVER_HEAD);
    out.push('\n');
    if uses_db(program) {
        out.push_str(DB_PRELUDE);
        out.push('\n');
    }
    if uses_auth(program) {
        out.push_str(CRYPTO_PRELUDE);
        out.push('\n');
    }
    // Signed `session` cookie (R24): the interpreter's HMAC-SHA256 signer, ported
    // verbatim so a cookie minted by `xeres serve` verifies here and vice-versa.
    if uses_session(program) {
        out.push_str(SESSION_PRELUDE);
        out.push('\n');
    }
    // Exact Decimal money (spec 18): rust_decimal helpers, gated behind `decimal`.
    if uses_decimal(program) {
        out.push_str(DECIMAL_PRELUDE);
        out.push('\n');
    }
    // Egress endpoints (R26): the ureq helpers + a fixed base const and bearer
    // loader per declaration. The host is baked in here, never caller-supplied.
    if !program.endpoints.is_empty() {
        out.push_str(HTTP_PRELUDE);
        out.push('\n');
        for ep in &program.endpoints {
            out.push_str(&format!(
                "const __EP_{}_BASE: &str = \"{}\";\n",
                ep.name.to_uppercase(),
                ep.base
            ));
            let bearer = match ep.secrets.first() {
                Some((f, _)) => format!(
                    "std::env::var(\"{}_{}\").unwrap_or_default()",
                    ep.name.to_uppercase(),
                    f.to_uppercase()
                ),
                None => "String::new()".to_string(),
            };
            out.push_str(&format!(
                "fn __ep_{}_bearer() -> String {{ {} }}\n",
                ep.name.to_lowercase(),
                bearer
            ));
        }
        out.push('\n');
    }

    // Enums are string-backed: the variant validity is proven by the checker
    // (R20), so the server tier carries them as `String` (wire = the variant).
    for e in &program.enums {
        let variants = e.variants.iter().map(|v| format!("// {}", v)).collect::<Vec<_>>().join(" ");
        out.push_str(&format!("pub type {} = String;  {}\n", e.name, variants));
    }
    if !program.enums.is_empty() {
        out.push('\n');
    }

    // Models: full fidelity (secrets stay server-side) + a wire projection that
    // OMITS secret fields. The wire codec is the runtime half of R3/R5.
    for m in &program.models {
        // `PartialEq` powers `List<Model>.contains` (spec 19). Not `Eq` — a model
        // may carry a `Float` field, which isn't `Eq`.
        out.push_str(&format!("#[derive(Debug, Clone, Default, PartialEq)]\npub struct {} {{\n", m.name));
        for p in &m.properties {
            let note = if p.is_secret { "  // secret — never leaves the server" } else { "" };
            out.push_str(&format!(
                "    pub {}: {},{}\n",
                p.name,
                map_rust_type(&p.data_type),
                note
            ));
        }
        out.push_str("}\n\n");

        // to_wire_json: build JSON from non-secret fields only.
        out.push_str(&format!("impl {} {{\n", m.name));
        out.push_str("    /// Serialize for the wire. `secret` fields are omitted by construction.\n");
        out.push_str("    pub fn to_wire_json(&self) -> String {\n");
        out.push_str("        let mut s = String::from(\"{\");\n");
        let mut first = true;
        for p in &m.properties {
            if p.is_secret {
                out.push_str(&format!("        // {} is secret — not serialized\n", p.name));
                continue;
            }
            if !first {
                out.push_str("        s.push(',');\n");
            }
            first = false;
            out.push_str(&format!("        s.push_str(\"\\\"{}\\\":\");\n", p.name));
            let path = format!("self.{}", p.name);
            out.push_str(&format!("        s.push_str(&{});\n", wire_serialize(&path, &p.data_type, &models)));
        }
        out.push_str("        s.push('}');\n");
        out.push_str("        s\n");
        out.push_str("    }\n}\n\n");
    }

    // Functions: only server (and unscoped) bodies live here.
    for f in &program.functions {
        if f.env == EnvModifier::Ui {
            out.push_str(&format!("// `{}` runs in the browser — see client.ts\n\n", f.name));
            continue;
        }
        let params = f
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, map_rust_type(&p.type_name)))
            .collect::<Vec<_>>()
            .join(", ");
        let ret = match &f.return_type {
            Some(t) => format!(" -> {}", map_rust_type(t)),
            None => String::new(),
        };
        out.push_str(&format!("pub fn {}({}){} {{\n", f.name, params, ret));
        for s in &f.body {
            out.push_str(&format!("    {}\n", emit_server_stmt(s, f, program)));
        }
        out.push_str("}\n\n");

        // RPC entry: runs the fn, then serializes the result through the wire
        // codec so secret fields are physically absent from the response.
        let arg_names = f.params.iter().map(|p| p.name.clone()).collect::<Vec<_>>().join(", ");
        out.push_str(&format!(
            "/// RPC entry for `{name}` — response goes through the wire projection.\n\
             pub fn {name}_rpc({params}) -> String {{\n\
             \x20   let __r = {name}({args});\n",
            name = f.name,
            params = params,
            args = arg_names
        ));
        let body = match &f.return_type {
            Some(t) => wire_serialize("__r", t, &models),
            None => "String::from(\"null\")".to_string(),
        };
        out.push_str(&format!("    {}\n}}\n\n", body));
    }

    // Inbound API (spec 23): per-route handler fns + the `api_dispatch` router.
    // Emitted only when the app declares an `api` block.
    if !program.apis.is_empty() {
        out.push_str(&gen_api(program, &models));
        out.push('\n');
    }

    // Sync endpoint. The store is generic (id -> raw row JSON, LWW by lamport),
    // so it needs no per-model code. Client rows are already secret-free
    // (the client interface omits secret fields).
    if program.states.is_empty() {
        out.push_str(
            "fn sync_dispatch(_coll: &str, _body: &str) -> String { String::from(\"{\\\"lamport\\\":0,\\\"ops\\\":[]}\") }\n\n",
        );
    } else {
        out.push_str(SYNC_SERVER);
        out.push('\n');
    }

    // Generated router: maps each server fn endpoint to its _rpc wrapper.
    // Args (scalars AND model objects) are decoded from the JSON body array.
    out.push_str("fn route(path: &str, body: &str) -> Option<(u16, String)> {\n");
    out.push_str("    let __a = jparse(body);\n");
    out.push_str("    match path {\n");
    for f in &program.functions {
        if f.env != EnvModifier::Server {
            continue;
        }
        let args = f
            .params
            .iter()
            .enumerate()
            .map(|(i, p)| arg_extractor(i, &p.type_name, program))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "        \"/__xeres/{name}\" => Some((200, {name}_rpc({args}))),\n",
            name = f.name,
            args = args
        ));
    }
    out.push_str("        _ => None,\n    }\n}\n\n");

    // Weave session cookie recovery + Set-Cookie into the request loop. The
    // actor is recovered from a verified `xeres_session` cookie into a per-request
    // thread-local (read by `session.actor`); a `session.login`/`logout` records a
    // pending Set-Cookie, taken out after dispatch. Non-session apps get neither.
    let server_main = if uses_session(program) {
        SERVER_MAIN
            .replace("    //__XERES_RECOVER__", SESSION_RECOVER)
            .replace("    //__XERES_SETCOOKIE__", SESSION_SETCOOKIE)
    } else {
        SERVER_MAIN
            .replace("    //__XERES_RECOVER__\n", "")
            .replace("    //__XERES_SETCOOKIE__\n", "")
    };
    // R31 auth-route guard: refuse the SPA shell for a protected route without a
    // verified session (the actor was recovered into the thread-local just above).
    // Mirrors the guard in src/serve.rs. Only an app with an `auth` route needs it.
    let has_auth_route =
        program.screens.iter().any(|s| s.is_auth && !s.is_component && s.params.is_empty());
    let server_main = if has_auth_route {
        out.push_str(&gen_protected_paths(program));
        server_main.replace("    //__XERES_GUARD__", AUTH_GUARD)
    } else {
        server_main.replace("    //__XERES_GUARD__\n", "")
    };
    // Inbound API dispatch (spec 23): match a declared route before the SPA shell
    // fallback. Api responses are always JSON.
    let server_main = if program.apis.is_empty() {
        server_main.replace("    //__XERES_API__\n", "")
    } else {
        server_main.replace(
            "    //__XERES_API__",
            "    if let Some((__c, __j)) = api_dispatch(method, path, body) { return (__c, \"application/json\", __j); }",
        )
    };
    // Security headers (F1): emit the shared `crate::protocol` constant so the
    // generated server's CSP/HSTS policy is byte-for-byte the interpreter host's
    // — one source, two consumers, can't drift.
    let server_main =
        server_main.replace("//__XERES_SECURITY_HEADERS__", &crate::protocol::emitted_security_headers_decl());
    out.push_str(&server_main);
    out
}

/// Inbound API codegen (spec 23). Emits one handler fn per route (typed like a
/// server fn) + an `api_dispatch(method, path, body)` router that decodes the
/// JSON-object body into the body model, runs the handler, and wire-projects the
/// response (so `secret` fields can't appear). `Optional<T>` return ⇒ `None` is
/// a 404. The client tier ignores `api` — this surface is for external callers.
fn gen_api(program: &XeresProgram, models: &HashSet<&str>) -> String {
    let mut out = String::new();
    // Per-route handler fns.
    for (ai, api) in program.apis.iter().enumerate() {
        for (ri, route) in api.routes.iter().enumerate() {
            let hname = format!("__api_{}_{}", ai, ri);
            let params = match &route.body {
                Some(b) => format!("{}: {}", b.name, map_rust_type(&b.type_name)),
                None => String::new(),
            };
            let ret = match &route.return_type {
                Some(t) => format!(" -> {}", map_rust_type(t)),
                None => String::new(),
            };
            let synth = FunctionNode {
                env: EnvModifier::Server,
                is_auth: false,
                name: hname.clone(),
                params: route
                    .body
                    .iter()
                    .map(|b| Param { name: b.name.clone(), type_name: b.type_name.clone() })
                    .collect(),
                return_type: route.return_type.clone(),
                body: route.body_stmts.clone(),
                line: route.line,
                is_pub: false,
                module: api.module.clone(),
            };
            out.push_str(&format!("pub fn {}({}){} {{\n", hname, params, ret));
            for s in &synth.body {
                out.push_str(&format!("    {}\n", emit_server_stmt(s, &synth, program)));
            }
            out.push_str("}\n\n");
        }
    }
    // The router.
    out.push_str("fn api_dispatch(method: &str, path: &str, body: &str) -> Option<(u16, String)> {\n");
    out.push_str("    let _ = body;\n"); // silence unused when no route has a body
    out.push_str("    let __hit = match (method, path) {\n");
    for (ai, api) in program.apis.iter().enumerate() {
        for (ri, route) in api.routes.iter().enumerate() {
            let hname = format!("__api_{}_{}", ai, ri);
            let full = format!("{}{}", api.base, route.path);
            let method = route.method.as_str();
            let (pre, call) = match &route.body {
                Some(b) => {
                    let decode = decode_json_rust("Some(&__b)", &b.type_name, program, 0);
                    (format!("let __b = jparse(body); let __arg = {}; ", decode), format!("{}(__arg)", hname))
                }
                None => (String::new(), format!("{}()", hname)),
            };
            let respond = match &route.return_type {
                Some(t) if generic_inner("Optional", t).is_some() => {
                    let inner = generic_inner("Optional", t).unwrap();
                    let ser = wire_serialize("__v", inner, models);
                    format!("match {call} {{ Some(__v) => Some((200, {ser})), None => Some((404, String::new())) }}")
                }
                Some(t) => {
                    let ser = wire_serialize("__r", t, models);
                    format!("let __r = {call}; Some((200, {ser}))")
                }
                None => format!("{call}; Some((200, String::from(\"null\")))"),
            };
            out.push_str(&format!("        (\"{method}\", \"{full}\") => {{ {pre}{respond} }}\n"));
        }
    }
    out.push_str("        _ => None,\n    };\n");
    out.push_str("    if __hit.is_some() { return __hit; }\n");
    // An unmatched path UNDER a declared base is a genuine API miss — return a
    // JSON 404 rather than falling through to the SPA shell (which would serve
    // HTML for a typo'd endpoint). Truly-unrelated paths return None (→ SPA).
    let mut bases: Vec<&str> = program.apis.iter().map(|a| a.base.as_str()).collect();
    bases.sort();
    bases.dedup();
    let guard = bases
        .iter()
        .map(|b| format!("path.starts_with(\"{}\")", b))
        .collect::<Vec<_>>()
        .join(" || ");
    out.push_str(&format!("    if {guard} {{\n"));
    out.push_str("        return Some((404, String::from(\"{\\\"error\\\":\\\"not found\\\"}\")));\n");
    out.push_str("    }\n    None\n}\n\n");
    out
}

/// R31 — the generated `is_protected_path`: the literal set of `auth` route paths,
/// mirroring the client router's path map (first prop-less screen `/`, rest
/// `/<name>`). The default route can't be `auth`, so these are all `/<name>`.
fn gen_protected_paths(program: &XeresProgram) -> String {
    let navigable: Vec<_> =
        program.screens.iter().filter(|s| !s.is_component && s.params.is_empty()).collect();
    let default = navigable.first().map(|s| s.name.clone()).unwrap_or_default();
    let arms: Vec<String> = navigable
        .iter()
        .filter(|s| s.is_auth)
        .map(|s| {
            let p = if s.name == default { "/".to_string() } else { format!("/{}", s.name.to_lowercase()) };
            format!("{:?}", p)
        })
        .collect();
    format!("fn is_protected_path(p: &str) -> bool {{ matches!(p, {}) }}\n\n", arms.join(" | "))
}

/// Recover the actor from a verified session cookie into the per-request
/// thread-local, before dispatch (session apps only). Mirrors `serve.rs`.
const SESSION_RECOVER: &str = "    let __actor = cookie_value(&req, \"xeres_session\").and_then(|c| session_verify(&c));\n    session_set_actor(__actor);";

/// Emit any Set-Cookie recorded by `session.login`/`logout` during the call,
/// before the CSRF cookie (session apps only). Mirrors `serve.rs`.
const SESSION_SETCOOKIE: &str = "    if let Some(c) = session_take_cookie() {\n        cookies.push_str(&format!(\"Set-Cookie: {}\\r\\n\", c));\n    }";

/// R31 — the generated auth-route guard, spliced into `dispatch` (only for apps
/// with an `auth` route). `session_actor()` was set by SESSION_RECOVER before
/// dispatch, so `None` means no valid session ⇒ bounce to the public root.
const AUTH_GUARD: &str = "    if method == \"GET\" && session_actor().is_none() && is_protected_path(path) {\n        return (302, \"text/html\", String::from(\"/\"));\n    }";

/// Rust expression decoding RPC argument `i` of type `ty` from the parsed JSON
/// array `__a`. Delegates to the recursive decoder, so an argument may be any
/// type in the grammar — scalar, model, `List<T>`, `Optional<T>`, or any nesting
/// (e.g. `List<Model>`, `Optional<Model>`, a model with a `List` field).
fn arg_extractor(i: usize, ty: &str, program: &XeresProgram) -> String {
    decode_json_rust(&format!("__a.idx({})", i), ty, program, 0)
}

/// Recursive JSON→Rust decoder. `src` is a Rust expression of type `Option<&J>`
/// (the value to decode; absent ⇒ the type's default). `depth` keeps generated
/// binding names unique across nesting. The runtime half of model-typed RPC
/// args — secret fields simply never appear in the client payload, so a missing
/// field defaults, exactly as before.
// `pub(super)` so the endpoint-response decoder in the core (`endpoint_map_expr`)
// can reuse this same JSON→Rust decoder (spec 24 / F1-style sharing).
pub(super) fn decode_json_rust(src: &str, ty: &str, program: &XeresProgram, depth: usize) -> String {
    if let Some(inner) = generic_inner("List", ty) {
        let ev = format!("__e{}", depth);
        let elem = decode_json_rust(&format!("Some({})", ev), inner, program, depth + 1);
        return format!(
            "(match {src} {{ Some(J::Arr(__v)) => __v.iter().map(|{ev}| {elem}).collect::<Vec<_>>(), _ => Vec::new() }})",
            src = src, ev = ev, elem = elem
        );
    }
    if let Some(inner) = generic_inner("Optional", ty) {
        let inner_dec = decode_json_rust("__s", inner, program, depth + 1);
        return format!(
            "(match {src} {{ None | Some(J::Null) => None, __s => Some({inner_dec}) }})",
            src = src, inner_dec = inner_dec
        );
    }
    if let Some(model) = program.models.iter().find(|m| m.name == ty) {
        let ov = format!("__o{}", depth);
        let fields = model
            .properties
            .iter()
            .map(|p| {
                let fsrc = format!("{}.and_then(|{ov}| {ov}.get(\"{f}\"))", src, ov = ov, f = p.name);
                format!("{}: {}", p.name, decode_json_rust(&fsrc, &p.data_type, program, depth + 1))
            })
            .collect::<Vec<_>>()
            .join(", ");
        return format!("{} {{ {} }}", ty, fields);
    }
    // String, Decimal (string-backed), and string-backed enums decode from JSON.
    if ty == "String" || ty == "Decimal" || program.enums.iter().any(|e| e.name == ty) {
        return format!("{}.map(|__v| __v.as_string()).unwrap_or_default()", src);
    }
    // scalar (Int, DateTime as i64; Float; Bool)
    match ty {
        "Float" => format!("{}.and_then(|__v| __v.as_f64()).unwrap_or(0.0)", src),
        "Bool" => format!("{}.map(|__v| __v.as_bool()).unwrap_or_default()", src),
        _ => format!("{}.map(|__v| __v.as_i64()).unwrap_or_default()", src),
    }
}

/// Rust expression (evaluating to `String`) that serializes `path` of type `ty`
/// for the wire. Models recurse through their own secret-stripping codec;
/// List -> JSON array, Optional -> value or null.
fn wire_serialize(path: &str, ty: &str, models: &HashSet<&str>) -> String {
    if let Some(inner) = generic_inner("List", ty) {
        let item = wire_serialize("__it", inner, models);
        return format!(
            "{{ let __v: Vec<String> = {}.iter().map(|__it| {}).collect(); format!(\"[{{}}]\", __v.join(\",\")) }}",
            path, item
        );
    }
    if let Some(inner) = generic_inner("Optional", ty) {
        let item = wire_serialize("__o", inner, models);
        return format!(
            "match &{} {{ Some(__o) => {}, None => String::from(\"null\") }}",
            path, item
        );
    }
    if models.contains(ty) {
        format!("{}.to_wire_json()", path)
    } else if matches!(ty, "Int" | "Float" | "Bool" | "DateTime") {
        // valid JSON number/bool scalars as-is
        format!("{}.to_string()", path)
    } else {
        // String and (string-backed) enums -> a JSON string
        format!("json_str(&{})", path)
    }
}

const SERVER_HEAD: &str = include_str!("../../../runtime/server_head.rs");

const SERVER_MAIN: &str = include_str!("../../../runtime/server_main.rs");

// Sync endpoint: a generic, field-level LWW store. Each row is a map of
// field -> Cell (the field's raw-JSON value + its own Lamport stamp + site id),
// so concurrent edits to different fields of a row both survive. A delete is a
// row tombstone with its own stamp; a row stays visible unless its tombstone
// dominates every field stamp, so a late (lower-stamped) write can't resurrect
// it. Stamps form a total order (higher Lamport wins, ties broken by the stable
// site id) ⇒ replicas converge regardless of arrival order. No per-model code —
// client rows are already secret-free. This MUST stay identical to the merge in
// `src/serve.rs` (the two run modes would otherwise diverge).
const SYNC_SERVER: &str = include_str!("../../../runtime/sync_server.rs");
