// src/codegen.rs
//
// Tier-splitting code generator. Runs AFTER the checker has proven the program
// boundary-safe, so codegen can assume every rule (R1..R6) already holds.
//
//   server.rs  — the server tier. Full model structs (secrets included),
//                real bodies for `server` fns. UI code does not exist here.
//
//   client.ts  — the browser tier. Model interfaces with `secret` fields
//                STRIPPED (they can never cross the wire), `ui` fns/screens as
//                real code, and every `server` fn replaced by a typed async RPC
//                stub — the dev never hand-writes a fetch.

use crate::parser::{
    BinOp, EnvModifier, Expr, FunctionNode, Handler, Stmt, UnOp, ViewNode, XeresProgram,
};
use std::collections::{HashMap, HashSet};

pub fn generate(
    program: &XeresProgram,
    _returns_secret: &HashMap<String, bool>,
) -> (String, String, String, String) {
    (
        gen_server(program),
        gen_client(program),
        gen_index(program),
        gen_cargo(program),
    )
}

/// The generated app's Cargo.toml. The `postgres` driver is added only when the
/// app actually uses `db` — db-free apps stay a zero-dependency std crate.
fn gen_cargo(program: &XeresProgram) -> String {
    let dep = if uses_db(program) {
        "\n[dependencies]\npostgres = \"0.19\"\n"
    } else {
        "\n"
    };
    format!(
        "[package]\nname = \"xeres-app\"\nversion = \"0.0.1\"\nedition = \"2021\"\n\n\
         [[bin]]\nname = \"xeres-app\"\npath = \"src/main.rs\"\n{}",
        dep
    )
}

/// Does any function body reference the `db` capability?
fn uses_db(program: &XeresProgram) -> bool {
    program.functions.iter().any(|f| f.body.iter().any(stmt_uses_db))
}
fn stmt_uses_db(s: &Stmt) -> bool {
    match s {
        Stmt::Let { value, .. }
        | Stmt::Assign { value, .. }
        | Stmt::Return(value)
        | Stmt::Expr(value) => expr_uses_db(value),
        Stmt::Try { body, handler } => {
            body.iter().any(stmt_uses_db) || handler.iter().any(stmt_uses_db)
        }
    }
}
fn expr_uses_db(e: &Expr) -> bool {
    match e {
        Expr::MethodCall { receiver, args, .. } => {
            matches!(receiver.as_ref(), Expr::Ident(n) if n == "db")
                || expr_uses_db(receiver)
                || args.iter().any(expr_uses_db)
        }
        Expr::Field { base, .. } => expr_uses_db(base),
        Expr::Call { args, .. } => args.iter().any(expr_uses_db),
        Expr::Unary { expr, .. } => expr_uses_db(expr),
        Expr::Binary { left, right, .. } => expr_uses_db(left) || expr_uses_db(right),
        Expr::Declassify(i) | Expr::Await(i) => expr_uses_db(i),
        Expr::Record { fields, .. } => fields.iter().any(|(_, v)| expr_uses_db(v)),
        Expr::ListLit(items) => items.iter().any(expr_uses_db),
        _ => false,
    }
}

// ------------------------------------------------------------------ server.rs

fn gen_server(program: &XeresProgram) -> String {
    let models: HashSet<&str> = program.models.iter().map(|m| m.name.as_str()).collect();

    let mut out = String::new();
    out.push_str("// GENERATED by xeres — server tier (std-only HTTP). Do not edit.\n");
    out.push_str("#![allow(dead_code, unused_variables)]\n\n");
    out.push_str(SERVER_HEAD);
    out.push('\n');
    if uses_db(program) {
        out.push_str(DB_PRELUDE);
        out.push('\n');
    }

    // Models: full fidelity (secrets stay server-side) + a wire projection that
    // OMITS secret fields. The wire codec is the runtime half of R3/R5.
    for m in &program.models {
        out.push_str(&format!("#[derive(Debug, Clone, Default)]\npub struct {} {{\n", m.name));
        for p in &m.properties {
            let note = if p.is_secret { "  // secret — never leaves the server" } else { "" };
            out.push_str(&format!(
                "    pub {}: {},{}\n",
                p.name,
                map_rust_type(&p.data_type),
                note
            ));
        }
        out.push_str("}\n\n");

        // to_wire_json: build JSON from non-secret fields only.
        out.push_str(&format!("impl {} {{\n", m.name));
        out.push_str("    /// Serialize for the wire. `secret` fields are omitted by construction.\n");
        out.push_str("    pub fn to_wire_json(&self) -> String {\n");
        out.push_str("        let mut s = String::from(\"{\");\n");
        let mut first = true;
        for p in &m.properties {
            if p.is_secret {
                out.push_str(&format!("        // {} is secret — not serialized\n", p.name));
                continue;
            }
            if !first {
                out.push_str("        s.push(',');\n");
            }
            first = false;
            out.push_str(&format!("        s.push_str(\"\\\"{}\\\":\");\n", p.name));
            let path = format!("self.{}", p.name);
            out.push_str(&format!("        s.push_str(&{});\n", wire_serialize(&path, &p.data_type, &models)));
        }
        out.push_str("        s.push('}');\n");
        out.push_str("        s\n");
        out.push_str("    }\n}\n\n");
    }

    // Functions: only server (and unscoped) bodies live here.
    for f in &program.functions {
        if f.env == EnvModifier::Ui {
            out.push_str(&format!("// `{}` runs in the browser — see client.ts\n\n", f.name));
            continue;
        }
        let params = f
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, map_rust_type(&p.type_name)))
            .collect::<Vec<_>>()
            .join(", ");
        let ret = match &f.return_type {
            Some(t) => format!(" -> {}", map_rust_type(t)),
            None => String::new(),
        };
        out.push_str(&format!("pub fn {}({}){} {{\n", f.name, params, ret));
        for s in &f.body {
            out.push_str(&format!("    {}\n", emit_server_stmt(s, f, program)));
        }
        out.push_str("}\n\n");

        // RPC entry: runs the fn, then serializes the result through the wire
        // codec so secret fields are physically absent from the response.
        let arg_names = f.params.iter().map(|p| p.name.clone()).collect::<Vec<_>>().join(", ");
        out.push_str(&format!(
            "/// RPC entry for `{name}` — response goes through the wire projection.\n\
             pub fn {name}_rpc({params}) -> String {{\n\
             \x20   let __r = {name}({args});\n",
            name = f.name,
            params = params,
            args = arg_names
        ));
        let body = match &f.return_type {
            Some(t) => wire_serialize("__r", t, &models),
            None => "String::from(\"null\")".to_string(),
        };
        out.push_str(&format!("    {}\n}}\n\n", body));
    }

    // Sync endpoint. The store is generic (id -> raw row JSON, LWW by lamport),
    // so it needs no per-model code. Client rows are already secret-free
    // (the client interface omits secret fields).
    if program.states.is_empty() {
        out.push_str(
            "fn sync_dispatch(_coll: &str, _body: &str) -> String { String::from(\"{\\\"lamport\\\":0,\\\"ops\\\":[]}\") }\n\n",
        );
    } else {
        out.push_str(SYNC_SERVER);
        out.push('\n');
    }

    // Generated router: maps each server fn endpoint to its _rpc wrapper.
    // Args (scalars AND model objects) are decoded from the JSON body array.
    out.push_str("fn route(path: &str, body: &str) -> Option<(u16, String)> {\n");
    out.push_str("    let __a = jparse(body);\n");
    out.push_str("    match path {\n");
    for f in &program.functions {
        if f.env != EnvModifier::Server {
            continue;
        }
        let args = f
            .params
            .iter()
            .enumerate()
            .map(|(i, p)| arg_extractor(i, &p.type_name, program))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "        \"/__xeres/{name}\" => Some((200, {name}_rpc({args}))),\n",
            name = f.name,
            args = args
        ));
    }
    out.push_str("        _ => None,\n    }\n}\n\n");

    out.push_str(SERVER_MAIN);
    out
}

/// Accessor method on a `J` value for a scalar type.
fn json_accessor(ty: &str) -> &'static str {
    match ty {
        "String" => "as_string",
        "Float" => "as_f64",
        "Bool" => "as_bool",
        _ => "as_i64", // Int
    }
}

/// Rust expression pulling argument `i` of type `ty` out of the parsed JSON
/// array `__a`. Scalars use accessors; models are built field-by-field.
fn arg_extractor(i: usize, ty: &str, program: &XeresProgram) -> String {
    if let Some(model) = program.models.iter().find(|m| m.name == ty) {
        // model arg: build from the JSON object at index i (missing/secret
        // fields default — the client never holds secret fields anyway).
        let fields = model
            .properties
            .iter()
            .map(|p| {
                let acc = json_accessor(&p.data_type);
                let is_generic = generic_inner("List", &p.data_type).is_some()
                    || generic_inner("Optional", &p.data_type).is_some();
                if is_generic || program.models.iter().any(|m| m.name == p.data_type) {
                    // nested model / generic — defaults for v0.1
                    format!("{}: Default::default()", p.name)
                } else {
                    format!(
                        "{n}: __a.idx({i}).and_then(|o| o.get(\"{n}\")).map(|v| v.{acc}()).unwrap_or_default()",
                        n = p.name, i = i, acc = acc
                    )
                }
            })
            .collect::<Vec<_>>()
            .join(", ");
        format!("{} {{ {} }}", ty, fields)
    } else {
        let acc = json_accessor(ty);
        format!("__a.idx({}).map(|v| v.{}()).unwrap_or_default()", i, acc)
    }
}

/// Rust expression (evaluating to `String`) that serializes `path` of type `ty`
/// for the wire. Models recurse through their own secret-stripping codec;
/// List -> JSON array, Optional -> value or null.
fn wire_serialize(path: &str, ty: &str, models: &HashSet<&str>) -> String {
    if let Some(inner) = generic_inner("List", ty) {
        let item = wire_serialize("__it", inner, models);
        return format!(
            "{{ let __v: Vec<String> = {}.iter().map(|__it| {}).collect(); format!(\"[{{}}]\", __v.join(\",\")) }}",
            path, item
        );
    }
    if let Some(inner) = generic_inner("Optional", ty) {
        let item = wire_serialize("__o", inner, models);
        return format!(
            "match &{} {{ Some(__o) => {}, None => String::from(\"null\") }}",
            path, item
        );
    }
    if models.contains(ty) {
        format!("{}.to_wire_json()", path)
    } else if ty == "String" {
        format!("json_str(&{})", path)
    } else {
        // Int, Float, Bool are valid JSON scalars as-is.
        format!("{}.to_string()", path)
    }
}

const SERVER_HEAD: &str = r#"use std::io::{Read, Write};
use std::net::{TcpListener, TcpStream};

/// Minimal JSON string escaping (spike-grade).
fn json_str(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

/// A JSON value + a recursive-descent parser (std-only). Shared by the RPC
/// router (to decode args, including model objects) and the sync endpoint.
enum J { Null, Bool(bool), Num(f64), Str(String), Arr(Vec<J>), Obj(Vec<(String, J)>) }
impl J {
    fn get(&self, k: &str) -> Option<&J> {
        if let J::Obj(v) = self { v.iter().find(|(kk, _)| kk == k).map(|(_, vv)| vv) } else { None }
    }
    fn idx(&self, i: usize) -> Option<&J> {
        if let J::Arr(v) = self { v.get(i) } else { None }
    }
    fn as_str(&self) -> Option<&str> { if let J::Str(s) = self { Some(s) } else { None } }
    fn as_f64(&self) -> Option<f64> { if let J::Num(n) = self { Some(*n) } else { None } }
    fn as_string(&self) -> String { self.as_str().unwrap_or("").to_string() }
    fn as_i64(&self) -> i64 { self.as_f64().unwrap_or(0.0) as i64 }
    fn as_bool(&self) -> bool { if let J::Bool(b) = self { *b } else { false } }
    fn to_json(&self) -> String {
        match self {
            J::Null => String::from("null"),
            J::Bool(b) => b.to_string(),
            J::Num(n) => if n.fract() == 0.0 { (*n as i64).to_string() } else { n.to_string() },
            J::Str(s) => json_str(s),
            J::Arr(a) => format!("[{}]", a.iter().map(|x| x.to_json()).collect::<Vec<_>>().join(",")),
            J::Obj(o) => format!("{{{}}}", o.iter().map(|(k, v)| format!("{}:{}", json_str(k), v.to_json())).collect::<Vec<_>>().join(",")),
        }
    }
}

fn jws(b: &[char], i: &mut usize) { while *i < b.len() && b[*i].is_whitespace() { *i += 1; } }
fn jstr(b: &[char], i: &mut usize) -> String {
    if *i < b.len() && b[*i] == '"' { *i += 1; }
    let mut s = String::new();
    while *i < b.len() && b[*i] != '"' {
        if b[*i] == '\\' && *i + 1 < b.len() {
            *i += 1;
            match b[*i] { 'n' => s.push('\n'), 't' => s.push('\t'), 'r' => s.push('\r'), c => s.push(c) }
        } else { s.push(b[*i]); }
        *i += 1;
    }
    if *i < b.len() { *i += 1; }
    s
}
fn jval(b: &[char], i: &mut usize) -> J {
    jws(b, i);
    if *i >= b.len() { return J::Null; }
    match b[*i] {
        '{' => {
            *i += 1;
            let mut o = Vec::new();
            loop {
                jws(b, i);
                if *i >= b.len() || b[*i] == '}' { if *i < b.len() { *i += 1; } break; }
                let k = jstr(b, i);
                jws(b, i);
                if *i < b.len() && b[*i] == ':' { *i += 1; }
                o.push((k, jval(b, i)));
                jws(b, i);
                if *i < b.len() && b[*i] == ',' { *i += 1; }
            }
            J::Obj(o)
        }
        '[' => {
            *i += 1;
            let mut a = Vec::new();
            loop {
                jws(b, i);
                if *i >= b.len() || b[*i] == ']' { if *i < b.len() { *i += 1; } break; }
                a.push(jval(b, i));
                jws(b, i);
                if *i < b.len() && b[*i] == ',' { *i += 1; }
            }
            J::Arr(a)
        }
        '"' => J::Str(jstr(b, i)),
        't' => { *i += 4; J::Bool(true) }
        'f' => { *i += 5; J::Bool(false) }
        'n' => { *i += 4; J::Null }
        _ => {
            let st = *i;
            while *i < b.len() && (b[*i].is_ascii_digit() || b[*i] == '-' || b[*i] == '+' || b[*i] == '.' || b[*i] == 'e' || b[*i] == 'E') { *i += 1; }
            if *i == st { *i += 1; return J::Null; }
            let s: String = b[st..*i].iter().collect();
            J::Num(s.parse().unwrap_or(0.0))
        }
    }
}
fn jparse(s: &str) -> J { let b: Vec<char> = s.chars().collect(); let mut i = 0; jval(&b, &mut i) }
"#;

const SERVER_MAIN: &str = r#"fn reason(code: u16) -> &'static str {
    match code { 200 => "OK", 404 => "Not Found", 501 => "Not Implemented", _ => "OK" }
}

fn serve_static(path: &str) -> (u16, &'static str, String) {
    let rel = if path == "/" { "index.html" } else { path.trim_start_matches('/') };
    let full = format!("static/{}", rel);
    let ctype = if full.ends_with(".js") { "text/javascript" }
        else if full.ends_with(".css") { "text/css" }
        else { "text/html; charset=utf-8" };
    match std::fs::read_to_string(&full) {
        Ok(c) => (200, ctype, c),
        Err(_) => (404, "text/html", String::from("<h1>404 - not found</h1>")),
    }
}

fn dispatch(method: &str, path: &str, body: &str) -> (u16, &'static str, String) {
    if method == "POST" && path.starts_with("/__xeres/sync/") {
        let coll = &path["/__xeres/sync/".len()..];
        return (200, "application/json", sync_dispatch(coll, body));
    }
    if method == "POST" && path.starts_with("/__xeres/") {
        return match route(path, body) {
            Some((code, json)) => (code, "application/json", json),
            None => (404, "application/json", String::from("{\"error\":\"no such rpc\"}")),
        };
    }
    serve_static(path)
}

fn handle_conn(stream: &mut TcpStream) -> std::io::Result<()> {
    let mut buf = vec![0u8; 65536];
    let n = stream.read(&mut buf)?;
    if n == 0 { return Ok(()); }
    let req = String::from_utf8_lossy(&buf[..n]).to_string();
    let first = req.lines().next().unwrap_or("");
    let mut parts = first.split_whitespace();
    let method = parts.next().unwrap_or("");
    let path = parts.next().unwrap_or("/");
    let body = req.splitn(2, "\r\n\r\n").nth(1).unwrap_or("");
    let (code, ctype, payload) = dispatch(method, path, body);
    let resp = format!(
        "HTTP/1.1 {} {}\r\nContent-Type: {}\r\nAccess-Control-Allow-Origin: *\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
        code, reason(code), ctype, payload.as_bytes().len(), payload
    );
    stream.write_all(resp.as_bytes())?;
    stream.flush()
}

fn main() {
    let addr = "127.0.0.1:8080";
    let listener = TcpListener::bind(addr).expect("xeres: cannot bind 127.0.0.1:8080");
    println!("xeres app serving http://{}", addr);
    for stream in listener.incoming() {
        if let Ok(mut s) = stream {
            // One thread per connection: an idle/slow socket (e.g. a browser's
            // speculative connection) must not block the accept loop.
            std::thread::spawn(move || { let _ = handle_conn(&mut s); });
        }
    }
}
"#;

// Sync endpoint: a generic id->row-JSON store, merged last-write-wins by a
// Lamport counter. No per-model code — client rows are already secret-free.
const SYNC_SERVER: &str = r#"use std::sync::{Mutex, OnceLock};

struct CollState { rows: std::collections::HashMap<String, (String, u64)>, lamport: u64 }
fn sync_store() -> &'static Mutex<std::collections::HashMap<String, CollState>> {
    static S: OnceLock<Mutex<std::collections::HashMap<String, CollState>>> = OnceLock::new();
    S.get_or_init(|| Mutex::new(std::collections::HashMap::new()))
}

fn sync_dispatch(coll: &str, body: &str) -> String {
    let req = jparse(body);
    let mut guard = sync_store().lock().unwrap();
    let cs = guard.entry(coll.to_string()).or_insert_with(|| CollState { rows: std::collections::HashMap::new(), lamport: 0 });
    if let Some(J::Arr(ops)) = req.get("ops") {
        for op in ops {
            let kind = op.get("kind").and_then(|j| j.as_str()).unwrap_or("");
            let id = op.get("id").and_then(|j| j.as_str()).unwrap_or("").to_string();
            if id.is_empty() { continue; }
            let lam = op.get("lamport").and_then(|j| j.as_f64()).unwrap_or(0.0) as u64;
            let seen = cs.rows.get(&id).map(|(_, v)| *v).unwrap_or(0);
            if lam < seen { continue; }
            if kind == "put" {
                let row = op.get("row").map(|j| j.to_json()).unwrap_or_else(|| String::from("null"));
                cs.rows.insert(id.clone(), (row, lam));
            } else if kind == "del" {
                cs.rows.insert(id.clone(), (String::from("null"), lam));
            }
            if lam > cs.lamport { cs.lamport = lam; }
        }
    }
    let mut out: Vec<String> = Vec::new();
    for (id, (row, v)) in cs.rows.iter() {
        if row == "null" {
            out.push(format!("{{\"kind\":\"del\",\"id\":{},\"row\":null,\"lamport\":{}}}", json_str(id), v));
        } else {
            out.push(format!("{{\"kind\":\"put\",\"id\":{},\"row\":{},\"lamport\":{}}}", json_str(id), row, v));
        }
    }
    out.sort();
    format!("{{\"lamport\":{},\"ops\":[{}]}}", cs.lamport, out.join(","))
}
"#;

// ------------------------------------------------------------------ client.ts

fn gen_client(program: &XeresProgram) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by xeres — browser tier. Do not edit.\n\n");
    out.push_str(RPC_RUNTIME);
    out.push('\n');
    out.push_str(UID_FN);
    out.push('\n');

    // Model interfaces — secret fields are STRIPPED. They never reach the client.
    for m in &program.models {
        out.push_str(&format!("export interface {} {{\n", m.name));
        for p in &m.properties {
            if p.is_secret {
                out.push_str(&format!("  // {}: <stripped> — secret never crosses the wire\n", p.name));
                continue;
            }
            out.push_str(&format!("  {}: {};\n", p.name, map_ts_type(&p.data_type)));
        }
        out.push_str("}\n\n");
    }

    // Functions.
    for f in &program.functions {
        match f.env {
            EnvModifier::Server => {
                // Server fn → typed async RPC stub. The compiler writes the fetch.
                let params = f
                    .params
                    .iter()
                    .map(|p| format!("{}: {}", p.name, map_ts_type(&p.type_name)))
                    .collect::<Vec<_>>()
                    .join(", ");
                let ret = f
                    .return_type
                    .as_deref()
                    .map(map_ts_type)
                    .unwrap_or_else(|| "void".to_string());
                let arg_names = f
                    .params
                    .iter()
                    .map(|p| p.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!(
                    "// server fn — runs server-side; this is the auto-generated call site.\n\
                     export async function {name}({params}): Promise<{ret}> {{\n\
                     \x20 return __rpc(\"{name}\", [{args}]);\n\
                     }}\n\n",
                    name = f.name,
                    params = params,
                    ret = ret,
                    args = arg_names
                ));
            }
            EnvModifier::Ui | EnvModifier::None => {
                let params = f
                    .params
                    .iter()
                    .map(|p| format!("{}: {}", p.name, map_ts_type(&p.type_name)))
                    .collect::<Vec<_>>()
                    .join(", ");
                let ret = f
                    .return_type
                    .as_deref()
                    .map(map_ts_type)
                    .unwrap_or_else(|| "void".to_string());
                // A fn that awaits a server RPC is async (returns a Promise).
                let (kw, ret_ty) = if stmts_have_await(&f.body) {
                    ("export async function", format!("Promise<{}>", ret))
                } else {
                    ("export function", ret)
                };
                out.push_str(&format!("{} {}({}): {} {{\n", kw, f.name, params, ret_ty));
                for s in &f.body {
                    out.push_str(&format!("  {}\n", emit_stmt(s, "const", true)));
                }
                out.push_str("}\n\n");
            }
        }
    }

    // DOM runtime FIRST so on()/mount() exist before screens register handlers.
    if !program.screens.is_empty() {
        out.push_str(MOUNT_RUNTIME);
        out.push('\n');
    }

    // Screens: state cells + inline handlers + a reactive render function.
    for sc in &program.screens {
        out.push_str(&gen_screen(sc));
    }

    // Local-first sync: the runtime + one reactive collection per `synced state`.
    if !program.states.is_empty() {
        out.push_str(SYNC_RUNTIME);
        out.push('\n');
        for st in &program.states {
            out.push_str(&format!(
                "export const {name} = new SyncedCollection<{ty}>(\"{name}\");\n",
                name = st.name,
                ty = st.collection_type
            ));
        }
        out.push('\n');
    }

    // Register zero-arg ui/none fns as named handlers, then auto-start.
    if !program.screens.is_empty() {
        for f in &program.functions {
            if f.env != EnvModifier::Server && f.params.is_empty() {
                out.push_str(&format!("on(\"{name}\", {name});\n", name = f.name));
            }
        }
        // Redraw the view whenever a synced collection changes (local or pulled).
        for st in &program.states {
            out.push_str(&format!(
                "{name}.subscribe(() => {{ if (__draw) __draw(); }});\n",
                name = st.name
            ));
        }
        if let Some(sc) = program.screens.iter().find(|s| s.params.is_empty()) {
            out.push_str(&format!(
                "\nexport function __start(rootId: string): void {{\n\
                 \x20 const el = document.getElementById(rootId);\n\
                 \x20 if (el) mount(el, () => {screen}());\n\
                 }}\n",
                screen = sc.name
            ));
        }
    }

    out
}

/// Emit one screen: its `state` object, inline click-handler functions, and a
/// reactive render function (re-reads state each draw).
fn gen_screen(sc: &crate::parser::ScreenNode) -> String {
    let mut out = String::new();
    let state_vars: HashSet<String> = sc.states.iter().map(|s| s.name.clone()).collect();

    if !sc.states.is_empty() {
        let inits = sc
            .states
            .iter()
            .map(|s| format!("{}: {}", s.name, emit_expr(&s.init, true)))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("const {}_state = {{ {} }};\n", sc.name, inits));
    }

    let mut em = ScreenEmit {
        screen: sc.name.clone(),
        state_vars,
        handlers: String::new(),
        hcount: 0,
        loop_ctx: None,
    };
    let render_expr = em.nodes(&sc.body);
    out.push_str(&em.handlers);

    let props = sc
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, map_ts_type(&p.type_name)))
        .collect::<Vec<_>>()
        .join(", ");
    let destr = if sc.states.is_empty() {
        String::new()
    } else {
        let names = sc
            .states
            .iter()
            .map(|s| s.name.clone())
            .collect::<Vec<_>>()
            .join(", ");
        format!("  const {{ {} }} = {}_state;\n", names, sc.name)
    };
    out.push_str(&format!(
        "export function {}({}): string {{\n{}  return {};\n}}\n\n",
        sc.name, props, destr, render_expr
    ));
    out
}

/// Walks a screen's view, allocating named handlers for inline `-> { ... }`
/// blocks and rewriting `state` reads/writes to the screen's state object.
struct ScreenEmit {
    screen: String,
    state_vars: HashSet<String>,
    handlers: String,
    hcount: usize,
    /// When inside `for var in coll`, the (var, coll) so handlers can key items.
    loop_ctx: Option<(String, String)>,
}

impl ScreenEmit {
    fn nodes(&mut self, nodes: &[ViewNode]) -> String {
        match nodes.len() {
            0 => "\"\"".to_string(),
            1 => self.node(&nodes[0]),
            _ => {
                let mut s = String::from("`");
                for n in nodes {
                    s.push_str("${");
                    s.push_str(&self.node(n));
                    s.push('}');
                }
                s.push('`');
                s
            }
        }
    }

    fn node(&mut self, v: &ViewNode) -> String {
        match v {
            ViewNode::Element { tag, arg, bind, event, children } => {
                let html = map_tag(tag);
                let void = is_void(html);
                let mut s = String::from("`<");
                s.push_str(html);
                match tag.as_str() {
                    "row" => s.push_str(" class=\"x-row\""),
                    "column" => s.push_str(" class=\"x-col\""),
                    _ => {}
                }
                match event {
                    Some(Handler::Call(e)) => {
                        s.push_str(" data-onclick=\"");
                        s.push_str(&emit_expr(e, true));
                        s.push('"');
                    }
                    Some(Handler::Block(stmts)) => {
                        let hname = format!("{}_h{}", self.screen, self.hcount);
                        self.hcount += 1;
                        let body: String = stmts
                            .iter()
                            .map(|st| emit_h_stmt(st, &self.screen, &self.state_vars))
                            .collect::<Vec<_>>()
                            .join(" ");
                        let kw = if stmts_have_await(stmts) { "async function" } else { "function" };
                        if let Some((var, coll)) = self.loop_ctx.clone() {
                            // Inside a `for`: bind the item from its key (event delegation).
                            self.handlers.push_str(&format!(
                                "{kw} {h}(__key) {{ const {v} = {c}.get(__key); {b} }}\non(\"{h}\", {h});\n",
                                kw = kw, h = hname, v = var, c = coll, b = body
                            ));
                            s.push_str(" data-onclick=\"");
                            s.push_str(&hname);
                            s.push_str("\" data-key=\"${");
                            s.push_str(&var);
                            s.push_str(".id}\"");
                        } else {
                            self.handlers.push_str(&format!(
                                "{kw} {h}() {{ {b} }}\non(\"{h}\", {h});\n",
                                kw = kw, h = hname, b = body
                            ));
                            s.push_str(" data-onclick=\"");
                            s.push_str(&hname);
                            s.push('"');
                        }
                    }
                    None => {}
                }
                // input placeholder from a string arg; `password` masks input
                if void {
                    if tag == "password" {
                        s.push_str(" type=\"password\"");
                    }
                    if let Some(Expr::Str(ph)) = arg {
                        s.push_str(" placeholder=\"");
                        s.push_str(ph);
                        s.push('"');
                    }
                }
                // two-way bind: value reflects state; oninput updates state.
                if let Some(var) = bind {
                    let bname = format!("{}:{}", self.screen, var);
                    self.handlers.push_str(&format!(
                        "onBind(\"{bn}\", (v) => {{ {sc}_state.{v} = v; }});\n",
                        bn = bname,
                        sc = self.screen,
                        v = var
                    ));
                    s.push_str(" value=\"${");
                    s.push_str(var);
                    s.push_str("}\" data-bind=\"");
                    s.push_str(&bname);
                    s.push('"');
                }
                if void {
                    s.push_str(" />`");
                    return s;
                }
                s.push('>');
                match arg {
                    Some(Expr::Str(t)) => s.push_str(t),
                    Some(e) => {
                        s.push_str("${");
                        s.push_str(&emit_expr(e, true));
                        s.push('}');
                    }
                    None => {}
                }
                for c in children {
                    s.push_str("${");
                    s.push_str(&self.node(c));
                    s.push('}');
                }
                s.push_str("</");
                s.push_str(html);
                s.push_str(">`");
                s
            }
            ViewNode::For { var, iter, body } => {
                // track (var, collection) so handlers in the body can key items
                let coll = if let Expr::Ident(c) = iter { Some(c.clone()) } else { None };
                let prev = self.loop_ctx.take();
                self.loop_ctx = coll.map(|c| (var.clone(), c));
                let body_js = self.nodes(body);
                self.loop_ctx = prev;
                format!(
                    "{}.all().map(({}) => {}).join(\"\")",
                    emit_expr(iter, true),
                    var,
                    body_js
                )
            }
            ViewNode::If { cond, then_body, else_body } => {
                let then_js = self.nodes(then_body);
                let else_js = self.nodes(else_body);
                format!("({} ? {} : {})", emit_expr(cond, true), then_js, else_js)
            }
        }
    }
}

/// Handler-statement emitter: rewrites `state` cells to `<Screen>_state.x`.
fn emit_h_stmt(s: &Stmt, screen: &str, sv: &HashSet<String>) -> String {
    match s {
        Stmt::Assign { name, value } => {
            let target = if sv.contains(name) {
                format!("{}_state.{}", screen, name)
            } else {
                name.clone()
            };
            format!("{} = {};", target, emit_h_expr(value, screen, sv))
        }
        Stmt::Let { name, value } => format!("let {} = {};", name, emit_h_expr(value, screen, sv)),
        Stmt::Return(e) => format!("return {};", emit_h_expr(e, screen, sv)),
        Stmt::Expr(e) => format!("{};", emit_h_expr(e, screen, sv)),
        Stmt::Try { body, handler } => {
            let b = body.iter().map(|x| emit_h_stmt(x, screen, sv)).collect::<Vec<_>>().join(" ");
            let h = handler.iter().map(|x| emit_h_stmt(x, screen, sv)).collect::<Vec<_>>().join(" ");
            format!("try {{ {} }} catch (_e) {{ {} }}", b, h)
        }
    }
}

fn emit_h_expr(e: &Expr, screen: &str, sv: &HashSet<String>) -> String {
    match e {
        Expr::Ident(v) => {
            if sv.contains(v) {
                format!("{}_state.{}", screen, v)
            } else {
                v.clone()
            }
        }
        Expr::Int(n) => n.to_string(),
        Expr::Float(f) => format!("{:?}", f),
        Expr::Str(s) => format!("{:?}", s),
        Expr::Bool(b) => b.to_string(),
        Expr::Field { base, field } => format!("{}.{}", emit_h_expr(base, screen, sv), field),
        Expr::Call { callee, args } => {
            let a = args
                .iter()
                .map(|x| emit_h_expr(x, screen, sv))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{}({})", callee, a)
        }
        Expr::Unary { op, expr } => {
            let sym = match op {
                UnOp::Neg => "-",
                UnOp::Not => "!",
            };
            format!("{}{}", sym, emit_h_expr(expr, screen, sv))
        }
        Expr::Binary { op, left, right } => format!(
            "({} {} {})",
            emit_h_expr(left, screen, sv),
            binop_sym(*op),
            emit_h_expr(right, screen, sv)
        ),
        Expr::Declassify(inner) => emit_h_expr(inner, screen, sv),
        Expr::Await(inner) => format!("await {}", emit_h_expr(inner, screen, sv)),
        Expr::MethodCall { receiver, method, args } => {
            if method == "or" && args.len() == 1 {
                return format!(
                    "({} ?? {})",
                    emit_h_expr(receiver, screen, sv),
                    emit_h_expr(&args[0], screen, sv)
                );
            }
            let a = args.iter().map(|x| emit_h_expr(x, screen, sv)).collect::<Vec<_>>().join(", ");
            format!("{}.{}({})", emit_h_expr(receiver, screen, sv), method, a)
        }
        Expr::NoneLit => "null".to_string(),
        Expr::ListLit(items) => {
            let body = items.iter().map(|x| emit_h_expr(x, screen, sv)).collect::<Vec<_>>().join(", ");
            format!("[{}]", body)
        }
        // Record in a handler is a client object literal; rewrite state refs.
        Expr::Record { fields, .. } => {
            let body = fields
                .iter()
                .map(|(f, v)| format!("{}: {}", f, emit_h_expr(v, screen, sv)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ {} }}", body)
        }
    }
}

/// Does a body / expression contain an `await` (so its fn must be `async`)?
fn stmts_have_await(stmts: &[Stmt]) -> bool {
    stmts.iter().any(|s| match s {
        Stmt::Let { value, .. }
        | Stmt::Assign { value, .. }
        | Stmt::Return(value)
        | Stmt::Expr(value) => expr_has_await(value),
        Stmt::Try { body, handler } => stmts_have_await(body) || stmts_have_await(handler),
    })
}

fn expr_has_await(e: &Expr) -> bool {
    match e {
        Expr::Await(_) => true,
        Expr::Field { base, .. } => expr_has_await(base),
        Expr::Call { args, .. } => args.iter().any(expr_has_await),
        Expr::Unary { expr, .. } => expr_has_await(expr),
        Expr::Binary { left, right, .. } => expr_has_await(left) || expr_has_await(right),
        Expr::Declassify(inner) => expr_has_await(inner),
        Expr::MethodCall { receiver, args, .. } => {
            expr_has_await(receiver) || args.iter().any(expr_has_await)
        }
        Expr::Record { fields, .. } => fields.iter().any(|(_, v)| expr_has_await(v)),
        Expr::ListLit(items) => items.iter().any(expr_has_await),
        Expr::Int(_) | Expr::Float(_) | Expr::Str(_) | Expr::Bool(_) | Expr::Ident(_)
        | Expr::NoneLit => false,
    }
}

const MOUNT_RUNTIME: &str = r#"// ---- xeres dom runtime ----
type XHandler = (key?: string) => void | Promise<void>;
const __handlers = new Map<string, XHandler>();
const __binds = new Map<string, (v: string) => void>();
let __draw: (() => void) | null = null;   // set by mount; called on reactive updates
export function on(name: string, fn: XHandler): void { __handlers.set(name, fn); }
export function onBind(name: string, fn: (v: string) => void): void { __binds.set(name, fn); }

// Render a screen into `el`, then wire events. Clicks re-render afterwards;
// input binds update state WITHOUT re-rendering (so the field keeps focus).
export function mount(el: HTMLElement, render: () => string): void {
  const draw = () => {
    el.innerHTML = render();
    el.querySelectorAll<HTMLElement>("[data-onclick]").forEach((node) => {
      const name = node.getAttribute("data-onclick") || "";
      const key = node.getAttribute("data-key") || undefined;
      node.onclick = async () => { const h = __handlers.get(name); if (h) await h(key); draw(); };
    });
    el.querySelectorAll<HTMLInputElement>("[data-bind]").forEach((node) => {
      const name = node.getAttribute("data-bind") || "";
      node.oninput = () => { const b = __binds.get(name); if (b) b(node.value); };
    });
  };
  __draw = draw;
  draw();
}
"#;

// ------------------------------------------------------------------ index.html

/// A branded "your app is running" dashboard, with the compiled program's
/// endpoints + schema baked in, and the first prop-less screen mounted below.
fn gen_index(program: &XeresProgram) -> String {
    let mut out = String::new();
    out.push_str(INDEX_HEAD);
    let first = program.screens.iter().find(|s| s.params.is_empty());
    if first.is_some() {
        out.push_str("<div id=\"app\"></div>");
    } else {
        out.push_str("<div id=\"app\" class=\"hint\">Add a <code>ui screen Name { … }</code> to app.xrs.</div>");
    }
    out.push_str("<footer>powered by <b>Xeres</b> · tier-safe web · zero framework runtime</footer>");
    out.push_str("</main>");
    if first.is_some() {
        out.push_str(
            "<script type=\"module\">import { __start } from \"./client.js\"; __start(\"app\");</script>",
        );
    }
    out.push_str("</body></html>");
    out
}

const INDEX_HEAD: &str = r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Xeres app</title>
<style>
:root { color-scheme: dark; }
* { box-sizing: border-box; }
body { margin: 0; min-height: 100vh; display: grid; place-items: center;
  font-family: system-ui, -apple-system, "Segoe UI", sans-serif; color: #e6e6ef;
  background: radial-gradient(900px 500px at 50% -10%, #241546 0%, #13151a 60%); }
.x-app { display: flex; flex-direction: column; align-items: center; text-align: center; padding: 2rem; gap: .25rem; }
.x-logo { font-size: 5rem; line-height: 1; margin-bottom: 1rem;
  background: linear-gradient(135deg, #a855f7, #6366f1); -webkit-background-clip: text; background-clip: text; color: transparent;
  filter: drop-shadow(0 0 26px rgba(124, 58, 237, .45)); }
#app h1 { font-size: 2.8rem; margin: .2rem 0; letter-spacing: -.02em; color: #c084fc; }
#app .x-col { display: flex; flex-direction: column; align-items: center; gap: .5rem; }
#app .x-row { display: flex; align-items: center; gap: .5rem; }
#app span { color: #a4a4c0; }
#app input { padding: .6rem .85rem; font-size: 1rem; border: 1px solid #3a3d48; border-radius: .5rem;
  background: #1c1f27; color: #e6e6ef; min-width: 18rem; }
#app input:focus { outline: none; border-color: #7c3aed; }
#app input::placeholder { color: #6f6f88; }
#app button { padding: .55rem 1.2rem; font-size: 1rem; border: 1px solid #7c3aed; border-radius: .5rem;
  background: #7c3aed; color: #fff; cursor: pointer; transition: background .15s; }
#app button:hover { background: #6d28d9; }
.hint { color: #7a7a96; }
.hint code { color: #d8b4fe; background: rgba(255,255,255,.06); padding: .1rem .4rem; border-radius: .3rem; }
footer { color: #6f6f88; font-size: .85rem; margin-top: 2rem; }
footer b { color: #a9a9c2; }
</style>
</head>
<body>
<main class="x-app">
<div class="x-logo">&#9670;</div>
"#;

const UID_FN: &str = r#"function uid(): string {
  return (typeof crypto !== "undefined" && crypto.randomUUID)
    ? crypto.randomUUID()
    : Date.now().toString(36) + Math.random().toString(36).slice(2);
}
"#;

const RPC_RUNTIME: &str = "\
async function __rpc<T>(name: string, args: unknown[]): Promise<T> {
  const res = await fetch(`/__xeres/${name}`, {
    method: \"POST\",
    headers: { \"content-type\": \"application/json\" },
    body: JSON.stringify(args),
  });
  if (!res.ok) throw new Error(`xeres rpc ${name} failed: ${res.status}`);
  return res.json() as Promise<T>;
}
";

// Local-first sync runtime. Shape: on-device store + offline oplog + network
// trawler, with last-write-wins merge by a Lamport counter. Swap MemoryStore
// for a sql.js / cr-sqlite adapter to get real on-device SQLite + CRDT merge.
const SYNC_RUNTIME: &str = r#"// ---- xeres local-first sync runtime (spike) ----
type XOpKind = "put" | "del";
interface XOp<T> { kind: XOpKind; id: string; row: T | null; lamport: number; }

export interface LocalStore<T> {
  load(): { rows: Map<string, T>; versions: Map<string, number>; lamport: number };
  persist(rows: Map<string, T>, versions: Map<string, number>, lamport: number): void;
}

// Default adapter: in-memory mirror, snapshotted to localStorage. Replace with a
// SQLite-backed adapter (sql.js / cr-sqlite) without changing SyncedCollection.
class MemoryStore<T> implements LocalStore<T> {
  constructor(private key: string) {}
  load() {
    try {
      const raw = typeof localStorage !== "undefined" ? localStorage.getItem(this.key) : null;
      if (raw) {
        const o = JSON.parse(raw);
        return {
          rows: new Map(Object.entries(o.rows ?? {})) as Map<string, T>,
          versions: new Map(Object.entries(o.versions ?? {})) as Map<string, number>,
          lamport: o.lamport ?? 0,
        };
      }
    } catch { /* fall through to empty */ }
    return { rows: new Map<string, T>(), versions: new Map<string, number>(), lamport: 0 };
  }
  persist(rows: Map<string, T>, versions: Map<string, number>, lamport: number) {
    if (typeof localStorage === "undefined") return;
    localStorage.setItem(this.key, JSON.stringify({
      rows: Object.fromEntries(rows),
      versions: Object.fromEntries(versions),
      lamport,
    }));
  }
}

export class SyncedCollection<T extends { id: string }> {
  private rows = new Map<string, T>();
  private versions = new Map<string, number>();
  private pending: XOp<T>[] = [];
  private lamport = 0;
  private subs = new Set<(rows: T[]) => void>();

  constructor(private name: string, private store: LocalStore<T> = new MemoryStore<T>("xeres:" + name)) {
    const snap = store.load();
    this.rows = snap.rows; this.versions = snap.versions; this.lamport = snap.lamport;
    if (typeof addEventListener !== "undefined") addEventListener("online", () => { void this.sync(); });
    if (typeof setInterval !== "undefined") setInterval(() => { void this.sync(); }, 2000); // trawler
  }

  all(): T[] { return [...this.rows.values()]; }
  get(id: string): T | undefined { return this.rows.get(id); }

  subscribe(fn: (rows: T[]) => void): () => void {
    this.subs.add(fn); fn(this.all());
    return () => { this.subs.delete(fn); };
  }

  add(row: T): void {
    this.lamport++;
    const op: XOp<T> = { kind: "put", id: row.id, row, lamport: this.lamport };
    this.applyLocal(op); this.pending.push(op); this.commit(); void this.sync();
  }

  remove(id: string): void {
    this.lamport++;
    const op: XOp<T> = { kind: "del", id, row: null, lamport: this.lamport };
    this.applyLocal(op); this.pending.push(op); this.commit(); void this.sync();
  }

  // Last-write-wins by Lamport counter. Returns whether state changed.
  private applyLocal(op: XOp<T>): boolean {
    const seen = this.versions.get(op.id) ?? -1;
    if (op.lamport < seen) return false;
    this.versions.set(op.id, op.lamport);
    if (op.kind === "del") this.rows.delete(op.id);
    else if (op.row) this.rows.set(op.id, op.row);
    return true;
  }

  private commit(): void {
    this.store.persist(this.rows, this.versions, this.lamport);
    const rows = this.all();
    this.subs.forEach((f) => f(rows));
  }

  // Network trawler step: flush the offline oplog, pull authoritative changes,
  // merge. Fully offline-safe — any failure leaves the queue intact for retry.
  async sync(): Promise<void> {
    if (typeof navigator !== "undefined" && navigator.onLine === false) return;
    let res: Response;
    try {
      res = await fetch(`/__xeres/sync/${this.name}`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ since: this.lamport, ops: this.pending }),
      });
    } catch { return; }
    if (!res.ok) return;
    const remote = (await res.json()) as { lamport: number; ops: XOp<T>[] };
    let changed = false;
    for (const op of remote.ops ?? []) changed = this.applyLocal(op) || changed;
    this.pending = [];
    this.lamport = Math.max(this.lamport, remote.lamport ?? this.lamport);
    if (changed) this.commit();
  }
}
"#;

// ------------------------------------------------------------------ shared

/// One expression printer for BOTH targets: the operators in this subset
/// (+ - * / == != < > <= >= && || ! and field access / calls) are spelled
/// identically in Rust and TypeScript.
fn emit_expr(e: &Expr, ts: bool) -> String {
    match e {
        Expr::Int(n) => n.to_string(),
        Expr::Float(f) => format!("{:?}", f),
        // Rust strings are owned end-to-end (fields, lists, returns all expect String).
        Expr::Str(s) => if ts { format!("{:?}", s) } else { format!("String::from({:?})", s) },
        Expr::Bool(b) => b.to_string(),
        Expr::Ident(v) => v.clone(),
        Expr::Field { base, field } => format!("{}.{}", emit_expr(base, ts), field),
        Expr::Call { callee, args } => {
            let a = args.iter().map(|x| emit_expr(x, ts)).collect::<Vec<_>>().join(", ");
            format!("{}({})", callee, a)
        }
        Expr::Unary { op, expr } => {
            let sym = match op {
                UnOp::Neg => "-",
                UnOp::Not => "!",
            };
            format!("{}{}", sym, emit_expr(expr, ts))
        }
        Expr::Binary { op, left, right } => {
            format!("({} {} {})", emit_expr(left, ts), binop_sym(*op), emit_expr(right, ts))
        }
        // declassify is a server-only, audited identity at the value level.
        Expr::Declassify(inner) => emit_expr(inner, ts),
        Expr::Await(inner) => format!("await {}", emit_expr(inner, ts)),
        Expr::MethodCall { receiver, method, args } => {
            // `db.*` compiles to Postgres helper calls (server tier only).
            if matches!(receiver.as_ref(), Expr::Ident(n) if n == "db") {
                let sql = args.first().map(|a| emit_expr(a, ts)).unwrap_or_else(|| "\"\"".into());
                let params = pg_params(args.get(1..).unwrap_or(&[]));
                return if method == "exec" {
                    format!("db_exec({}, {})", sql, params)
                } else {
                    format!("db_query({}, {})", sql, params)
                };
            }
            // `optional.or(default)` — TS `??`, Rust `unwrap_or`.
            if method == "or" && args.len() == 1 {
                let r = emit_expr(receiver, ts);
                let d = emit_expr(&args[0], ts);
                return if ts {
                    format!("({} ?? {})", r, d)
                } else {
                    format!("{}.clone().unwrap_or({})", r, d)
                };
            }
            let a = args.iter().map(|x| emit_expr(x, ts)).collect::<Vec<_>>().join(", ");
            format!("{}.{}({})", emit_expr(receiver, ts), method, a)
        }
        Expr::NoneLit => if ts { "null".to_string() } else { "None".to_string() },
        Expr::ListLit(items) => {
            let body = items.iter().map(|x| emit_expr(x, ts)).collect::<Vec<_>>().join(", ");
            if ts {
                format!("[{}]", body)
            } else {
                format!("vec![{}]", body)
            }
        }
        // Record literal. TS: a plain object. Rust: fields pass through
        // `.into()` (covers T -> T and the T -> Option<T> coercion) and any
        // omitted Optional/List fields are filled by struct update.
        Expr::Record { name, fields } => {
            if ts {
                let body = fields
                    .iter()
                    .map(|(f, v)| format!("{}: {}", f, emit_expr(v, ts)))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{{ {} }}", body)
            } else {
                let body = fields
                    .iter()
                    .map(|(f, v)| format!("{}: ({}).into()", f, emit_expr(v, ts)))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{} {{ {}, ..Default::default() }}", name, body)
            }
        }
    }
}

fn emit_stmt(s: &Stmt, let_kw: &str, ts: bool) -> String {
    match s {
        Stmt::Let { name, value } => format!("{} {} = {};", let_kw, name, emit_expr(value, ts)),
        Stmt::Assign { name, value } => format!("{} = {};", name, emit_expr(value, ts)),
        Stmt::Return(e) => format!("return {};", emit_expr(e, ts)),
        Stmt::Expr(e) => format!("{};", emit_expr(e, ts)),
        // browser-only (checker R16); the Rust tier never sees a Try.
        Stmt::Try { body, handler } => {
            let b = body.iter().map(|x| emit_stmt(x, let_kw, ts)).collect::<Vec<_>>().join(" ");
            let h = handler.iter().map(|x| emit_stmt(x, let_kw, ts)).collect::<Vec<_>>().join(" ");
            format!("try {{ {} }} catch (_e) {{ {} }}", b, h)
        }
    }
}

/// Postgres parameter list: `&[&arg as &(dyn ToSql + Sync), ...]`.
fn pg_params(args: &[Expr]) -> String {
    if args.is_empty() {
        return "&[]".to_string();
    }
    let items = args
        .iter()
        .map(|a| format!("&{} as &(dyn ToSql + Sync)", emit_expr(a, false)))
        .collect::<Vec<_>>()
        .join(", ");
    format!("&[{}]", items)
}

/// Server-side statement emitter. Special-cases `return db.query_one(sql, ...)`
/// to map the first row onto the function's return model; otherwise normal.
fn emit_server_stmt(s: &Stmt, f: &FunctionNode, program: &XeresProgram) -> String {
    if let Stmt::Return(Expr::MethodCall { receiver, method, args }) = s {
        let is_db = matches!(receiver.as_ref(), Expr::Ident(n) if n == "db");
        if is_db && method == "query_one" {
            if let Some(model_name) = &f.return_type {
                if let Some(model) = program.models.iter().find(|m| &m.name == model_name) {
                    let sql = args.first().map(|a| emit_expr(a, false)).unwrap_or_else(|| "\"\"".into());
                    let params = pg_params(args.get(1..).unwrap_or(&[]));
                    let fields = model
                        .properties
                        .iter()
                        .map(|p| format!("{n}: __r.get(\"{n}\")", n = p.name))
                        .collect::<Vec<_>>()
                        .join(", ");
                    return format!(
                        "return {{ let __rows = db_query({sql}, {params}); \
                         let __r = __rows.into_iter().next().expect(\"xeres: query_one returned no rows\"); \
                         {model} {{ {fields} }} }};",
                        sql = sql, params = params, model = model_name, fields = fields
                    );
                }
            }
        }
    }
    emit_stmt(s, "let", false)
}

const DB_PRELUDE: &str = r#"use postgres::types::ToSql;

fn db_client() -> postgres::Client {
    let url = std::env::var("DATABASE_URL").expect("xeres: DATABASE_URL is not set");
    postgres::Client::connect(&url, postgres::NoTls).expect("xeres: database connection failed")
}
fn db_exec(sql: &str, params: &[&(dyn ToSql + Sync)]) -> i64 {
    db_client().execute(sql, params).map(|n| n as i64).unwrap_or(0)
}
fn db_query(sql: &str, params: &[&(dyn ToSql + Sync)]) -> Vec<postgres::Row> {
    db_client().query(sql, params).expect("xeres: database query failed")
}
"#;

fn binop_sym(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Eq => "==",
        BinOp::NotEq => "!=",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::LtEq => "<=",
        BinOp::GtEq => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
    }
}

/// Inner type of a one-level generic, e.g. `("List", "List<User>") -> "User"`.
fn generic_inner<'a>(base: &str, ty: &'a str) -> Option<&'a str> {
    ty.strip_prefix(base)
        .and_then(|r| r.strip_prefix('<'))
        .and_then(|r| r.strip_suffix('>'))
}

fn map_rust_type(name: &str) -> String {
    if let Some(inner) = generic_inner("List", name) {
        return format!("Vec<{}>", map_rust_type(inner));
    }
    if let Some(inner) = generic_inner("Optional", name) {
        return format!("Option<{}>", map_rust_type(inner));
    }
    match name {
        "String" => "String".to_string(),
        "Int" => "i64".to_string(),
        "Float" => "f64".to_string(),
        "Bool" => "bool".to_string(),
        other => other.to_string(),
    }
}

fn map_ts_type(name: &str) -> String {
    if let Some(inner) = generic_inner("List", name) {
        return format!("{}[]", map_ts_type(inner));
    }
    if let Some(inner) = generic_inner("Optional", name) {
        return format!("({} | null)", map_ts_type(inner));
    }
    match name {
        "String" => "string".to_string(),
        "Int" | "Float" => "number".to_string(),
        "Bool" => "boolean".to_string(),
        other => other.to_string(),
    }
}

/// HTML void elements have no children/closing tag.
fn is_void(html_tag: &str) -> bool {
    matches!(html_tag, "input" | "br" | "img" | "hr")
}

fn map_tag(tag: &str) -> &str {
    match tag {
        "column" => "div",
        "row" => "div",
        "heading" => "h1",
        "text" => "span",
        "button" => "button",
        "password" => "input",
        other => other,
    }
}
