// src/protocol.rs
//
// One source of truth for the HTTP protocol surface shared by the two server
// implementations: the live interpreter host (`src/serve.rs`) and the emitted
// std-only Rust server (`runtime/server_main.rs`, generated by `codegen`).
//
// Before this (review F1) the security-header block was copied verbatim in both
// files — so a CSP/HSTS/nosniff change had to land in two places and only the
// `serve.rs` copy was under test. They would drift. Now `serve.rs` uses this
// constant directly and `codegen` emits the *same* constant into the generated
// server (via the `//__XERES_SECURITY_HEADERS__` placeholder), so the two can no
// longer diverge. Mirrors the `src/json.rs` extraction (spec 24, F1's cure).

/// Default S1/S2 security headers, sent on every response. Strict CSP backstops
/// R22 — inline script is forbidden; inline style is allowed for the language's
/// `style=""`. HSTS is always set (honored once TLS terminates in front).
/// `Access-Control-Allow-Origin` is intentionally absent — the app is
/// same-origin. The trailing `\r\n` closes the block; callers append their own
/// `Content-Length`/`Connection` lines after it.
pub const SECURITY_HEADERS: &str = "X-Content-Type-Options: nosniff\r\n\
    Referrer-Policy: no-referrer\r\n\
    X-Frame-Options: DENY\r\n\
    Strict-Transport-Security: max-age=63072000; includeSubDomains\r\n\
    Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'\r\n";

/// The exact source text codegen substitutes for the `//__XERES_SECURITY_HEADERS__`
/// placeholder in `runtime/server_main.rs`: the two-line doc comment plus a
/// `const SECURITY_HEADERS` whose literal is generated from [`SECURITY_HEADERS`]
/// (never hand-copied). `{:?}` on a `&str` yields a correctly-escaped Rust
/// string literal, so the emitted server gets byte-for-byte the same policy the
/// interpreter host enforces.
pub fn emitted_security_headers_decl() -> String {
    format!(
        "// Default S1/S2 security headers, always emitted. HSTS is honored once TLS is\n\
         // terminated in front; no Access-Control-Allow-Origin (the app is same-origin).\n\
         const SECURITY_HEADERS: &str = {:?};",
        SECURITY_HEADERS
    )
}
